<?php 

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXButton;

/**
* @method UIxButton setArmed($mixed)
* @method UIxButton _setText(mixed $arg0)
* @method UIxButton _setAlignment( $arg0)
* @method UIxButton _setGraphicTextGap(mixed $arg0)
* @method UIxButton _setContentDisplay( $arg0)
* @method UIxButton _setTextAlignment( $arg0)
* @method UIxButton _setMnemonicParsing(mixed $arg0)
* @method UIxButton _setWrapText(mixed $arg0)
* @method UIxButton _setUnderline(mixed $arg0)
* @method UIxButton _setEllipsisString(mixed $arg0)
* @method UIxButton _setFont(php\gui\text\UXFont $arg0)
* @method UIxButton _setGraphic(php\gui\UXNode $arg0)
* @method UIxButton _setTextColor(mixed $arg0)
* @method UIxButton setResizable($mixed)
* @method UIxButton _setTooltip(php\gui\UXTooltip $arg0)
* @method UIxButton _setContextMenu(php\gui\UXContextMenu $arg0)
* @method UIxButton _setTooltipText(mixed $arg0)
* @method UIxButton _setMinHeight(mixed $arg0)
* @method UIxButton _setMaxWidth(mixed $arg0)
* @method UIxButton _setMinWidth(mixed $arg0)
* @method UIxButton _setMaxHeight(mixed $arg0)
* @method UIxButton _setPadding(mixed $arg0)
* @method UIxButton _setMinSize(array $arg0)
* @method UIxButton _setMaxSize(array $arg0)
* @method UIxButton _setBackgroundColor(mixed $arg0)
* @method UIxButton _setPaddingTop(mixed $arg0)
* @method UIxButton setPrefSize($mixed)
* @method UIxButton _setPaddingLeft(mixed $arg0)
* @method UIxButton _setPaddingRight(mixed $arg0)
* @method UIxButton _setPaddingBottom(mixed $arg0)
* @method UIxButton setStylesheets($mixed)
* @method UIxButton setChildrenUnmodifiable($mixed)
* @method UIxButton _setCache(mixed $arg0)
* @method UIxButton _setRotate(mixed $arg0)
* @method UIxButton _setId(mixed $arg0)
* @method UIxButton _setOpacity(mixed $arg0)
* @method UIxButton _setStyle(mixed $arg0)
* @method UIxButton setFocused($mixed)
* @method UIxButton _setManaged(mixed $arg0)
* @method UIxButton setPressed($mixed)
* @method UIxButton setHover($mixed)
* @method UIxButton _setVisible(mixed $arg0)
* @method UIxButton setDisabled($mixed)
* @method UIxButton setClasses($mixed)
* @method UIxButton _setPickOnBounds(mixed $arg0)
* @method UIxButton _setBlendMode( $arg0)
* @method UIxButton _setFocusTraversable(mixed $arg0)
* @method UIxButton _setScaleX(mixed $arg0)
* @method UIxButton _setScaleY(mixed $arg0)
* @method UIxButton _setTranslateX(mixed $arg0)
* @method UIxButton _setTranslateY(mixed $arg0)
* @method UIxButton _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxButton setBaselineOffset($mixed)
* @method UIxButton _setClip(php\gui\UXNode $arg0)
* @method UIxButton _setDepthTest( $arg0)
* @method UIxButton _setScaleZ(mixed $arg0)
* @method UIxButton _setTranslateZ(mixed $arg0)
* @method UIxButton _setCacheHint( $arg0)
* @method UIxButton _setMouseTransparent(mixed $arg0)
* @method UIxButton setContentBias($mixed)
* @method UIxButton setParent($mixed)
* @method UIxButton _setSize(array $arg0)
* @method UIxButton setLayoutBounds($mixed)
* @method UIxButton _setWidth(mixed $arg0)
* @method UIxButton setScene($mixed)
* @method UIxButton setBoundsInParent($mixed)
* @method UIxButton _setX(mixed $arg0)
* @method UIxButton _setY(mixed $arg0)
* @method UIxButton _setCursor(mixed $arg0)
* @method UIxButton _setUserData(mixed $arg0)
* @method UIxButton _setPosition(array $arg0)
* @method UIxButton _setScale(mixed $arg0)
* @method UIxButton _setHeight(mixed $arg0)
* @method UIxButton setWindow($mixed)
* @method UIxButton _setEnabled(mixed $arg0)
* @method UIxButton setForm($mixed)
* @method UIxButton _setScreenPosition(array $arg0)
* @method UIxButton _setScreenX(mixed $arg0)
* @method UIxButton _setScreenY(mixed $arg0)
* @method UIxButton setEffects($mixed)
* @method UIxButton _setAnchorFlags(array $arg0)
* @method UIxButton _setClassesString(mixed $arg0)
* @method UIxButton _setAnchors(array $arg0)
* @method UIxButton _setLeftAnchor(mixed $arg0)
* @method UIxButton _setRightAnchor(mixed $arg0)
* @method UIxButton _setBottomAnchor(mixed $arg0)
* @method UIxButton _setTopAnchor(mixed $arg0)
 */
class UIxButton extends UXButton
{
    use Cascadable;


    
}