<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXComboBox;

/**
* @method UIxComboBox setEditor($mixed)
* @method UIxComboBox _setItems(php\gui\UXList $arg0)
* @method UIxComboBox _setVisibleRowCount(mixed $arg0)
* @method UIxComboBox _setText(mixed $arg0)
* @method UIxComboBox _setSelected(mixed $arg0)
* @method UIxComboBox _setItemsText(mixed $arg0)
* @method UIxComboBox _setSelectedIndex(mixed $arg0)
* @method UIxComboBox setShowing($mixed)
* @method UIxComboBox _setPromptText(mixed $arg0)
* @method UIxComboBox setArmed($mixed)
* @method UIxComboBox _setEditable(mixed $arg0)
* @method UIxComboBox _setValue(mixed $arg0)
* @method UIxComboBox _setPopupVisible(mixed $arg0)
* @method UIxComboBox setResizable($mixed)
* @method UIxComboBox _setTooltip(php\gui\UXTooltip $arg0)
* @method UIxComboBox _setContextMenu(php\gui\UXContextMenu $arg0)
* @method UIxComboBox _setTooltipText(mixed $arg0)
* @method UIxComboBox _setMinHeight(mixed $arg0)
* @method UIxComboBox _setMinWidth(mixed $arg0)
* @method UIxComboBox _setMaxWidth(mixed $arg0)
* @method UIxComboBox _setMaxHeight(mixed $arg0)
* @method UIxComboBox _setPadding(mixed $arg0)
* @method UIxComboBox _setMaxSize(array $arg0)
* @method UIxComboBox _setMinSize(array $arg0)
* @method UIxComboBox _setBackgroundColor(mixed $arg0)
* @method UIxComboBox _setPaddingTop(mixed $arg0)
* @method UIxComboBox _setPaddingLeft(mixed $arg0)
* @method UIxComboBox _setPaddingRight(mixed $arg0)
* @method UIxComboBox setPrefSize($mixed)
* @method UIxComboBox _setPaddingBottom(mixed $arg0)
* @method UIxComboBox setStylesheets($mixed)
* @method UIxComboBox setChildrenUnmodifiable($mixed)
* @method UIxComboBox _setCache(mixed $arg0)
* @method UIxComboBox _setRotate(mixed $arg0)
* @method UIxComboBox _setId(mixed $arg0)
* @method UIxComboBox _setOpacity(mixed $arg0)
* @method UIxComboBox setPressed($mixed)
* @method UIxComboBox _setStyle(mixed $arg0)
* @method UIxComboBox setHover($mixed)
* @method UIxComboBox _setVisible(mixed $arg0)
* @method UIxComboBox setFocused($mixed)
* @method UIxComboBox setDisabled($mixed)
* @method UIxComboBox _setManaged(mixed $arg0)
* @method UIxComboBox setClasses($mixed)
* @method UIxComboBox _setBlendMode( $arg0)
* @method UIxComboBox _setPickOnBounds(mixed $arg0)
* @method UIxComboBox _setFocusTraversable(mixed $arg0)
* @method UIxComboBox _setScaleX(mixed $arg0)
* @method UIxComboBox _setScaleY(mixed $arg0)
* @method UIxComboBox _setTranslateX(mixed $arg0)
* @method UIxComboBox _setTranslateY(mixed $arg0)
* @method UIxComboBox setBaselineOffset($mixed)
* @method UIxComboBox _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxComboBox _setClip(php\gui\UXNode $arg0)
* @method UIxComboBox _setDepthTest( $arg0)
* @method UIxComboBox _setScaleZ(mixed $arg0)
* @method UIxComboBox setContentBias($mixed)
* @method UIxComboBox _setTranslateZ(mixed $arg0)
* @method UIxComboBox _setMouseTransparent(mixed $arg0)
* @method UIxComboBox _setCacheHint( $arg0)
* @method UIxComboBox setParent($mixed)
* @method UIxComboBox _setSize(array $arg0)
* @method UIxComboBox setLayoutBounds($mixed)
* @method UIxComboBox _setWidth(mixed $arg0)
* @method UIxComboBox setScene($mixed)
* @method UIxComboBox setBoundsInParent($mixed)
* @method UIxComboBox _setCursor(mixed $arg0)
* @method UIxComboBox _setUserData(mixed $arg0)
* @method UIxComboBox _setX(mixed $arg0)
* @method UIxComboBox _setY(mixed $arg0)
* @method UIxComboBox _setPosition(array $arg0)
* @method UIxComboBox _setScale(mixed $arg0)
* @method UIxComboBox _setHeight(mixed $arg0)
* @method UIxComboBox setWindow($mixed)
* @method UIxComboBox _setScreenPosition(array $arg0)
* @method UIxComboBox _setEnabled(mixed $arg0)
* @method UIxComboBox _setScreenY(mixed $arg0)
* @method UIxComboBox _setScreenX(mixed $arg0)
* @method UIxComboBox _setLeftAnchor(mixed $arg0)
* @method UIxComboBox _setAnchors(array $arg0)
* @method UIxComboBox _setClassesString(mixed $arg0)
* @method UIxComboBox _setRightAnchor(mixed $arg0)
* @method UIxComboBox setEffects($mixed)
* @method UIxComboBox _setTopAnchor(mixed $arg0)
* @method UIxComboBox _setBottomAnchor(mixed $arg0)
* @method UIxComboBox _setAnchorFlags(array $arg0)
* @method UIxComboBox setForm($mixed) */

class UIxComboBox extends UXComboBox {
    use Cascadable;
}
