<?php 

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXChoiceBox;

/**
* @method UIxChoiceBox _setValue(mixed $arg0)
* @method UIxChoiceBox _setItems(php\gui\UXList $arg0)
* @method UIxChoiceBox _setSelectedIndex(mixed $arg0)
* @method UIxChoiceBox setResizable($mixed)
* @method UIxChoiceBox _setTooltip(php\gui\UXTooltip $arg0)
* @method UIxChoiceBox _setContextMenu(php\gui\UXContextMenu $arg0)
* @method UIxChoiceBox _setTooltipText(mixed $arg0)
* @method UIxChoiceBox _setMinHeight(mixed $arg0)
* @method UIxChoiceBox _setMaxWidth(mixed $arg0)
* @method UIxChoiceBox _setMinWidth(mixed $arg0)
* @method UIxChoiceBox _setMaxHeight(mixed $arg0)
* @method UIxChoiceBox _setPadding(mixed $arg0)
* @method UIxChoiceBox _setMinSize(array $arg0)
* @method UIxChoiceBox _setMaxSize(array $arg0)
* @method UIxChoiceBox _setBackgroundColor(mixed $arg0)
* @method UIxChoiceBox setPrefSize($mixed)
* @method UIxChoiceBox _setPaddingLeft(mixed $arg0)
* @method UIxChoiceBox _setPaddingRight(mixed $arg0)
* @method UIxChoiceBox _setPaddingTop(mixed $arg0)
* @method UIxChoiceBox _setPaddingBottom(mixed $arg0)
* @method UIxChoiceBox setStylesheets($mixed)
* @method UIxChoiceBox setChildrenUnmodifiable($mixed)
* @method UIxChoiceBox _setCache(mixed $arg0)
* @method UIxChoiceBox _setRotate(mixed $arg0)
* @method UIxChoiceBox _setId(mixed $arg0)
* @method UIxChoiceBox _setOpacity(mixed $arg0)
* @method UIxChoiceBox setHover($mixed)
* @method UIxChoiceBox _setManaged(mixed $arg0)
* @method UIxChoiceBox _setVisible(mixed $arg0)
* @method UIxChoiceBox setPressed($mixed)
* @method UIxChoiceBox setFocused($mixed)
* @method UIxChoiceBox setDisabled($mixed)
* @method UIxChoiceBox _setStyle(mixed $arg0)
* @method UIxChoiceBox setClasses($mixed)
* @method UIxChoiceBox _setBlendMode( $arg0)
* @method UIxChoiceBox _setPickOnBounds(mixed $arg0)
* @method UIxChoiceBox _setFocusTraversable(mixed $arg0)
* @method UIxChoiceBox _setScaleX(mixed $arg0)
* @method UIxChoiceBox _setScaleY(mixed $arg0)
* @method UIxChoiceBox _setTranslateX(mixed $arg0)
* @method UIxChoiceBox _setTranslateY(mixed $arg0)
* @method UIxChoiceBox _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxChoiceBox setBaselineOffset($mixed)
* @method UIxChoiceBox _setClip(php\gui\UXNode $arg0)
* @method UIxChoiceBox _setDepthTest( $arg0)
* @method UIxChoiceBox _setScaleZ(mixed $arg0)
* @method UIxChoiceBox _setTranslateZ(mixed $arg0)
* @method UIxChoiceBox _setCacheHint( $arg0)
* @method UIxChoiceBox _setMouseTransparent(mixed $arg0)
* @method UIxChoiceBox setContentBias($mixed)
* @method UIxChoiceBox setParent($mixed)
* @method UIxChoiceBox _setSize(array $arg0)
* @method UIxChoiceBox setLayoutBounds($mixed)
* @method UIxChoiceBox setScene($mixed)
* @method UIxChoiceBox _setWidth(mixed $arg0)
* @method UIxChoiceBox setBoundsInParent($mixed)
* @method UIxChoiceBox _setCursor(mixed $arg0)
* @method UIxChoiceBox _setUserData(mixed $arg0)
* @method UIxChoiceBox _setX(mixed $arg0)
* @method UIxChoiceBox _setY(mixed $arg0)
* @method UIxChoiceBox _setPosition(array $arg0)
* @method UIxChoiceBox _setScale(mixed $arg0)
* @method UIxChoiceBox _setHeight(mixed $arg0)
* @method UIxChoiceBox setWindow($mixed)
* @method UIxChoiceBox setForm($mixed)
* @method UIxChoiceBox _setEnabled(mixed $arg0)
* @method UIxChoiceBox _setScreenPosition(array $arg0)
* @method UIxChoiceBox _setScreenX(mixed $arg0)
* @method UIxChoiceBox _setScreenY(mixed $arg0)
* @method UIxChoiceBox _setClassesString(mixed $arg0)
* @method UIxChoiceBox _setTopAnchor(mixed $arg0)
* @method UIxChoiceBox _setAnchorFlags(array $arg0)
* @method UIxChoiceBox _setLeftAnchor(mixed $arg0)
* @method UIxChoiceBox setEffects($mixed)
* @method UIxChoiceBox _setRightAnchor(mixed $arg0)
* @method UIxChoiceBox _setAnchors(array $arg0)
* @method UIxChoiceBox _setBottomAnchor(mixed $arg0)
 */
class UIxChoiceBox extends UXChoiceBox
{
    use Cascadable;


    
}