<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXCheckbox;

/**
* @method UIxCheckBox _setSelected(mixed $arg0)
* @method UIxCheckBox _setAllowIndeterminate(mixed $arg0)
* @method UIxCheckBox _setIndeterminate(mixed $arg0)
* @method UIxCheckBox setArmed($mixed)
* @method UIxCheckBox _setText(mixed $arg0)
* @method UIxCheckBox _setAlignment( $arg0)
* @method UIxCheckBox _setWrapText(mixed $arg0)
* @method UIxCheckBox _setTextAlignment( $arg0)
* @method UIxCheckBox _setGraphicTextGap(mixed $arg0)
* @method UIxCheckBox _setContentDisplay( $arg0)
* @method UIxCheckBox _setMnemonicParsing(mixed $arg0)
* @method UIxCheckBox _setUnderline(mixed $arg0)
* @method UIxCheckBox _setEllipsisString(mixed $arg0)
* @method UIxCheckBox _setFont(php\gui\text\UXFont $arg0)
* @method UIxCheckBox _setGraphic(php\gui\UXNode $arg0)
* @method UIxCheckBox _setTextColor(mixed $arg0)
* @method UIxCheckBox setResizable($mixed)
* @method UIxCheckBox _setTooltip(php\gui\UXTooltip $arg0)
* @method UIxCheckBox _setContextMenu(php\gui\UXContextMenu $arg0)
* @method UIxCheckBox _setTooltipText(mixed $arg0)
* @method UIxCheckBox _setMinHeight(mixed $arg0)
* @method UIxCheckBox _setMaxWidth(mixed $arg0)
* @method UIxCheckBox _setMinWidth(mixed $arg0)
* @method UIxCheckBox _setMaxHeight(mixed $arg0)
* @method UIxCheckBox _setPadding(mixed $arg0)
* @method UIxCheckBox _setMinSize(array $arg0)
* @method UIxCheckBox _setMaxSize(array $arg0)
* @method UIxCheckBox _setBackgroundColor(mixed $arg0)
* @method UIxCheckBox _setPaddingTop(mixed $arg0)
* @method UIxCheckBox setPrefSize($mixed)
* @method UIxCheckBox _setPaddingBottom(mixed $arg0)
* @method UIxCheckBox _setPaddingRight(mixed $arg0)
* @method UIxCheckBox _setPaddingLeft(mixed $arg0)
* @method UIxCheckBox setStylesheets($mixed)
* @method UIxCheckBox setChildrenUnmodifiable($mixed)
* @method UIxCheckBox _setCache(mixed $arg0)
* @method UIxCheckBox _setRotate(mixed $arg0)
* @method UIxCheckBox _setId(mixed $arg0)
* @method UIxCheckBox _setOpacity(mixed $arg0)
* @method UIxCheckBox _setStyle(mixed $arg0)
* @method UIxCheckBox setDisabled($mixed)
* @method UIxCheckBox _setVisible(mixed $arg0)
* @method UIxCheckBox _setManaged(mixed $arg0)
* @method UIxCheckBox setFocused($mixed)
* @method UIxCheckBox setPressed($mixed)
* @method UIxCheckBox setHover($mixed)
* @method UIxCheckBox _setFocusTraversable(mixed $arg0)
* @method UIxCheckBox _setBlendMode( $arg0)
* @method UIxCheckBox _setPickOnBounds(mixed $arg0)
* @method UIxCheckBox setClasses($mixed)
* @method UIxCheckBox _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxCheckBox setBaselineOffset($mixed)
* @method UIxCheckBox _setScaleX(mixed $arg0)
* @method UIxCheckBox _setScaleY(mixed $arg0)
* @method UIxCheckBox _setTranslateX(mixed $arg0)
* @method UIxCheckBox _setTranslateY(mixed $arg0)
* @method UIxCheckBox _setClip(php\gui\UXNode $arg0)
* @method UIxCheckBox _setDepthTest( $arg0)
* @method UIxCheckBox _setScaleZ(mixed $arg0)
* @method UIxCheckBox _setTranslateZ(mixed $arg0)
* @method UIxCheckBox _setMouseTransparent(mixed $arg0)
* @method UIxCheckBox _setCacheHint( $arg0)
* @method UIxCheckBox setContentBias($mixed)
* @method UIxCheckBox setParent($mixed)
* @method UIxCheckBox _setSize(array $arg0)
* @method UIxCheckBox setLayoutBounds($mixed)
* @method UIxCheckBox _setWidth(mixed $arg0)
* @method UIxCheckBox setScene($mixed)
* @method UIxCheckBox setBoundsInParent($mixed)
* @method UIxCheckBox _setX(mixed $arg0)
* @method UIxCheckBox _setY(mixed $arg0)
* @method UIxCheckBox _setUserData(mixed $arg0)
* @method UIxCheckBox _setCursor(mixed $arg0)
* @method UIxCheckBox _setPosition(array $arg0)
* @method UIxCheckBox _setScale(mixed $arg0)
* @method UIxCheckBox _setHeight(mixed $arg0)
* @method UIxCheckBox setWindow($mixed)
* @method UIxCheckBox setForm($mixed)
* @method UIxCheckBox _setEnabled(mixed $arg0)
* @method UIxCheckBox _setScreenPosition(array $arg0)
* @method UIxCheckBox _setScreenX(mixed $arg0)
* @method UIxCheckBox _setScreenY(mixed $arg0)
* @method UIxCheckBox _setRightAnchor(mixed $arg0)
* @method UIxCheckBox _setLeftAnchor(mixed $arg0)
* @method UIxCheckBox _setTopAnchor(mixed $arg0)
* @method UIxCheckBox _setBottomAnchor(mixed $arg0)
* @method UIxCheckBox _setClassesString(mixed $arg0)
* @method UIxCheckBox _setAnchorFlags(array $arg0)
* @method UIxCheckBox setEffects($mixed)
* @method UIxCheckBox _setAnchors(array $arg0) */

class UIxCheckBox extends UXCheckbox {
    use Cascadable;
}
