<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXDatePicker;

/**
* @method UIxDatePicker setEditor($mixed)
* @method UIxDatePicker _setShowWeekNumbers(mixed $arg0)
* @method UIxDatePicker _setFormat(mixed $arg0)
* @method UIxDatePicker _setValueAsTime(mixed $arg0)
* @method UIxDatePicker setShowing($mixed)
* @method UIxDatePicker setArmed($mixed)
* @method UIxDatePicker _setEditable(mixed $arg0)
* @method UIxDatePicker _setPromptText(mixed $arg0)
* @method UIxDatePicker _setValue(mixed $arg0)
* @method UIxDatePicker _setPopupVisible(mixed $arg0)
* @method UIxDatePicker setResizable($mixed)
* @method UIxDatePicker _setTooltip(php\gui\UXTooltip $arg0)
* @method UIxDatePicker _setContextMenu(php\gui\UXContextMenu $arg0)
* @method UIxDatePicker _setTooltipText(mixed $arg0)
* @method UIxDatePicker _setMinWidth(mixed $arg0)
* @method UIxDatePicker _setMaxWidth(mixed $arg0)
* @method UIxDatePicker _setMinHeight(mixed $arg0)
* @method UIxDatePicker _setMaxHeight(mixed $arg0)
* @method UIxDatePicker _setPadding(mixed $arg0)
* @method UIxDatePicker _setMinSize(array $arg0)
* @method UIxDatePicker _setMaxSize(array $arg0)
* @method UIxDatePicker _setBackgroundColor(mixed $arg0)
* @method UIxDatePicker _setPaddingBottom(mixed $arg0)
* @method UIxDatePicker _setPaddingLeft(mixed $arg0)
* @method UIxDatePicker _setPaddingTop(mixed $arg0)
* @method UIxDatePicker _setPaddingRight(mixed $arg0)
* @method UIxDatePicker setPrefSize($mixed)
* @method UIxDatePicker setStylesheets($mixed)
* @method UIxDatePicker setChildrenUnmodifiable($mixed)
* @method UIxDatePicker _setCache(mixed $arg0)
* @method UIxDatePicker _setRotate(mixed $arg0)
* @method UIxDatePicker _setId(mixed $arg0)
* @method UIxDatePicker _setScaleX(mixed $arg0)
* @method UIxDatePicker _setScaleY(mixed $arg0)
* @method UIxDatePicker _setTranslateX(mixed $arg0)
* @method UIxDatePicker _setTranslateY(mixed $arg0)
* @method UIxDatePicker _setOpacity(mixed $arg0)
* @method UIxDatePicker _setStyle(mixed $arg0)
* @method UIxDatePicker _setManaged(mixed $arg0)
* @method UIxDatePicker _setVisible(mixed $arg0)
* @method UIxDatePicker setDisabled($mixed)
* @method UIxDatePicker setFocused($mixed)
* @method UIxDatePicker setHover($mixed)
* @method UIxDatePicker setPressed($mixed)
* @method UIxDatePicker _setPickOnBounds(mixed $arg0)
* @method UIxDatePicker _setBlendMode( $arg0)
* @method UIxDatePicker setClasses($mixed)
* @method UIxDatePicker _setFocusTraversable(mixed $arg0)
* @method UIxDatePicker _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxDatePicker setBaselineOffset($mixed)
* @method UIxDatePicker _setClip(php\gui\UXNode $arg0)
* @method UIxDatePicker _setDepthTest( $arg0)
* @method UIxDatePicker _setScaleZ(mixed $arg0)
* @method UIxDatePicker setContentBias($mixed)
* @method UIxDatePicker _setCacheHint( $arg0)
* @method UIxDatePicker _setTranslateZ(mixed $arg0)
* @method UIxDatePicker _setMouseTransparent(mixed $arg0)
* @method UIxDatePicker setParent($mixed)
* @method UIxDatePicker _setSize(array $arg0)
* @method UIxDatePicker _setWidth(mixed $arg0)
* @method UIxDatePicker setScene($mixed)
* @method UIxDatePicker setLayoutBounds($mixed)
* @method UIxDatePicker _setX(mixed $arg0)
* @method UIxDatePicker _setY(mixed $arg0)
* @method UIxDatePicker setBoundsInParent($mixed)
* @method UIxDatePicker _setUserData(mixed $arg0)
* @method UIxDatePicker _setCursor(mixed $arg0)
* @method UIxDatePicker _setPosition(array $arg0)
* @method UIxDatePicker _setScale(mixed $arg0)
* @method UIxDatePicker _setHeight(mixed $arg0)
* @method UIxDatePicker setWindow($mixed)
* @method UIxDatePicker _setEnabled(mixed $arg0)
* @method UIxDatePicker setForm($mixed)
* @method UIxDatePicker _setScreenPosition(array $arg0)
* @method UIxDatePicker _setScreenY(mixed $arg0)
* @method UIxDatePicker _setScreenX(mixed $arg0)
* @method UIxDatePicker _setAnchors(array $arg0)
* @method UIxDatePicker _setClassesString(mixed $arg0)
* @method UIxDatePicker _setBottomAnchor(mixed $arg0)
* @method UIxDatePicker _setAnchorFlags(array $arg0)
* @method UIxDatePicker setEffects($mixed)
* @method UIxDatePicker _setRightAnchor(mixed $arg0)
* @method UIxDatePicker _setLeftAnchor(mixed $arg0)
* @method UIxDatePicker _setTopAnchor(mixed $arg0) */

class UIxDatePicker extends UXDatePicker {
    use Cascadable;
}
