<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\shape\UXEllipse;

/**
* @method UIxEllipse _setRadiusX(mixed $arg0)
* @method UIxEllipse _setRadiusY(mixed $arg0)
* @method UIxEllipse _setSmooth(mixed $arg0)
* @method UIxEllipse _setStrokeWidth(mixed $arg0)
* @method UIxEllipse _setStrokeType( $arg0)
* @method UIxEllipse _setStrokeColor(mixed $arg0)
* @method UIxEllipse _setFillColor(mixed $arg0)
* @method UIxEllipse _setCache(mixed $arg0)
* @method UIxEllipse _setRotate(mixed $arg0)
* @method UIxEllipse _setId(mixed $arg0)
* @method UIxEllipse _setOpacity(mixed $arg0)
* @method UIxEllipse _setVisible(mixed $arg0)
* @method UIxEllipse _setStyle(mixed $arg0)
* @method UIxEllipse setPressed($mixed)
* @method UIxEllipse _setManaged(mixed $arg0)
* @method UIxEllipse setDisabled($mixed)
* @method UIxEllipse setHover($mixed)
* @method UIxEllipse setFocused($mixed)
* @method UIxEllipse setClasses($mixed)
* @method UIxEllipse _setPickOnBounds(mixed $arg0)
* @method UIxEllipse _setBlendMode( $arg0)
* @method UIxEllipse _setFocusTraversable(mixed $arg0)
* @method UIxEllipse setResizable($mixed)
* @method UIxEllipse _setScaleX(mixed $arg0)
* @method UIxEllipse _setScaleY(mixed $arg0)
* @method UIxEllipse _setTranslateX(mixed $arg0)
* @method UIxEllipse _setTranslateY(mixed $arg0)
* @method UIxEllipse _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxEllipse setBaselineOffset($mixed)
* @method UIxEllipse _setClip(php\gui\UXNode $arg0)
* @method UIxEllipse _setDepthTest( $arg0)
* @method UIxEllipse _setScaleZ(mixed $arg0)
* @method UIxEllipse _setTranslateZ(mixed $arg0)
* @method UIxEllipse _setMouseTransparent(mixed $arg0)
* @method UIxEllipse _setCacheHint( $arg0)
* @method UIxEllipse setContentBias($mixed)
* @method UIxEllipse setParent($mixed)
* @method UIxEllipse _setSize(array $arg0)
* @method UIxEllipse setLayoutBounds($mixed)
* @method UIxEllipse setScene($mixed)
* @method UIxEllipse _setWidth(mixed $arg0)
* @method UIxEllipse setBoundsInParent($mixed)
* @method UIxEllipse _setX(mixed $arg0)
* @method UIxEllipse _setY(mixed $arg0)
* @method UIxEllipse _setCursor(mixed $arg0)
* @method UIxEllipse _setUserData(mixed $arg0)
* @method UIxEllipse _setScale(mixed $arg0)
* @method UIxEllipse _setHeight(mixed $arg0)
* @method UIxEllipse setWindow($mixed)
* @method UIxEllipse _setPosition(array $arg0)
* @method UIxEllipse _setEnabled(mixed $arg0)
* @method UIxEllipse setForm($mixed)
* @method UIxEllipse _setScreenPosition(array $arg0)
* @method UIxEllipse _setScreenX(mixed $arg0)
* @method UIxEllipse _setScreenY(mixed $arg0)
* @method UIxEllipse _setAnchorFlags(array $arg0)
* @method UIxEllipse _setAnchors(array $arg0)
* @method UIxEllipse _setRightAnchor(mixed $arg0)
* @method UIxEllipse setEffects($mixed)
* @method UIxEllipse _setClassesString(mixed $arg0)
* @method UIxEllipse _setLeftAnchor(mixed $arg0)
* @method UIxEllipse _setTopAnchor(mixed $arg0)
* @method UIxEllipse _setBottomAnchor(mixed $arg0) */

class UIxEllipse extends UXEllipse {
    use Cascadable;
}
