<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\layout\UXFlowPane;

/**
* @method UIxFlowPane _setAlignment( $arg0)
* @method UIxFlowPane _setHgap(mixed $arg0)
* @method UIxFlowPane _setVgap(mixed $arg0)
* @method UIxFlowPane _setPrefWrapLength(mixed $arg0)
* @method UIxFlowPane _setColumnHalignment( $arg0)
* @method UIxFlowPane _setRowValignment( $arg0)
* @method UIxFlowPane _setOrientation( $arg0)
* @method UIxFlowPane setChildren($mixed)
* @method UIxFlowPane _setMinHeight(mixed $arg0)
* @method UIxFlowPane _setMinWidth(mixed $arg0)
* @method UIxFlowPane _setMaxWidth(mixed $arg0)
* @method UIxFlowPane _setMaxHeight(mixed $arg0)
* @method UIxFlowPane _setPadding(mixed $arg0)
* @method UIxFlowPane _setMaxSize(array $arg0)
* @method UIxFlowPane _setMinSize(array $arg0)
* @method UIxFlowPane _setBackgroundColor(mixed $arg0)
* @method UIxFlowPane setPrefSize($mixed)
* @method UIxFlowPane _setPaddingTop(mixed $arg0)
* @method UIxFlowPane _setPaddingLeft(mixed $arg0)
* @method UIxFlowPane _setPaddingBottom(mixed $arg0)
* @method UIxFlowPane _setPaddingRight(mixed $arg0)
* @method UIxFlowPane setStylesheets($mixed)
* @method UIxFlowPane setChildrenUnmodifiable($mixed)
* @method UIxFlowPane _setCache(mixed $arg0)
* @method UIxFlowPane _setRotate(mixed $arg0)
* @method UIxFlowPane _setId(mixed $arg0)
* @method UIxFlowPane _setScaleX(mixed $arg0)
* @method UIxFlowPane _setScaleY(mixed $arg0)
* @method UIxFlowPane _setTranslateX(mixed $arg0)
* @method UIxFlowPane _setTranslateY(mixed $arg0)
* @method UIxFlowPane _setOpacity(mixed $arg0)
* @method UIxFlowPane _setStyle(mixed $arg0)
* @method UIxFlowPane setDisabled($mixed)
* @method UIxFlowPane _setManaged(mixed $arg0)
* @method UIxFlowPane _setVisible(mixed $arg0)
* @method UIxFlowPane setHover($mixed)
* @method UIxFlowPane setPressed($mixed)
* @method UIxFlowPane setFocused($mixed)
* @method UIxFlowPane _setBlendMode( $arg0)
* @method UIxFlowPane setClasses($mixed)
* @method UIxFlowPane _setPickOnBounds(mixed $arg0)
* @method UIxFlowPane _setFocusTraversable(mixed $arg0)
* @method UIxFlowPane setResizable($mixed)
* @method UIxFlowPane _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxFlowPane setBaselineOffset($mixed)
* @method UIxFlowPane _setClip(php\gui\UXNode $arg0)
* @method UIxFlowPane _setScaleZ(mixed $arg0)
* @method UIxFlowPane _setDepthTest( $arg0)
* @method UIxFlowPane _setTranslateZ(mixed $arg0)
* @method UIxFlowPane _setMouseTransparent(mixed $arg0)
* @method UIxFlowPane _setCacheHint( $arg0)
* @method UIxFlowPane setContentBias($mixed)
* @method UIxFlowPane setParent($mixed)
* @method UIxFlowPane _setSize(array $arg0)
* @method UIxFlowPane setLayoutBounds($mixed)
* @method UIxFlowPane _setWidth(mixed $arg0)
* @method UIxFlowPane setScene($mixed)
* @method UIxFlowPane _setX(mixed $arg0)
* @method UIxFlowPane _setY(mixed $arg0)
* @method UIxFlowPane setBoundsInParent($mixed)
* @method UIxFlowPane _setUserData(mixed $arg0)
* @method UIxFlowPane _setCursor(mixed $arg0)
* @method UIxFlowPane _setScale(mixed $arg0)
* @method UIxFlowPane _setHeight(mixed $arg0)
* @method UIxFlowPane setWindow($mixed)
* @method UIxFlowPane _setPosition(array $arg0)
* @method UIxFlowPane setForm($mixed)
* @method UIxFlowPane _setEnabled(mixed $arg0)
* @method UIxFlowPane _setScreenPosition(array $arg0)
* @method UIxFlowPane _setScreenX(mixed $arg0)
* @method UIxFlowPane _setScreenY(mixed $arg0)
* @method UIxFlowPane _setLeftAnchor(mixed $arg0)
* @method UIxFlowPane setEffects($mixed)
* @method UIxFlowPane _setBottomAnchor(mixed $arg0)
* @method UIxFlowPane _setAnchors(array $arg0)
* @method UIxFlowPane _setClassesString(mixed $arg0)
* @method UIxFlowPane _setAnchorFlags(array $arg0)
* @method UIxFlowPane _setRightAnchor(mixed $arg0)
* @method UIxFlowPane _setTopAnchor(mixed $arg0) */

class UIxFlowPane extends UXFlowPane {
    use Cascadable;
}
