<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXFlatButton;

/**
* @method UIxFlatButton _setColor(mixed $arg0)
* @method UIxFlatButton _setBorderRadius(mixed $arg0)
* @method UIxFlatButton _setClickColor(mixed $arg0)
* @method UIxFlatButton _setHoverColor(mixed $arg0)
* @method UIxFlatButton setArmed($mixed)
* @method UIxFlatButton _setAlignment( $arg0)
* @method UIxFlatButton _setText(mixed $arg0)
* @method UIxFlatButton _setWrapText(mixed $arg0)
* @method UIxFlatButton _setContentDisplay( $arg0)
* @method UIxFlatButton _setGraphicTextGap(mixed $arg0)
* @method UIxFlatButton _setTextAlignment( $arg0)
* @method UIxFlatButton _setMnemonicParsing(mixed $arg0)
* @method UIxFlatButton _setUnderline(mixed $arg0)
* @method UIxFlatButton _setEllipsisString(mixed $arg0)
* @method UIxFlatButton _setFont(php\gui\text\UXFont $arg0)
* @method UIxFlatButton _setGraphic(php\gui\UXNode $arg0)
* @method UIxFlatButton _setTextColor(mixed $arg0)
* @method UIxFlatButton setResizable($mixed)
* @method UIxFlatButton _setTooltip(php\gui\UXTooltip $arg0)
* @method UIxFlatButton _setContextMenu(php\gui\UXContextMenu $arg0)
* @method UIxFlatButton _setTooltipText(mixed $arg0)
* @method UIxFlatButton _setMinHeight(mixed $arg0)
* @method UIxFlatButton _setMaxWidth(mixed $arg0)
* @method UIxFlatButton _setMinWidth(mixed $arg0)
* @method UIxFlatButton _setMaxHeight(mixed $arg0)
* @method UIxFlatButton _setPadding(mixed $arg0)
* @method UIxFlatButton _setMinSize(array $arg0)
* @method UIxFlatButton _setMaxSize(array $arg0)
* @method UIxFlatButton _setBackgroundColor(mixed $arg0)
* @method UIxFlatButton _setPaddingTop(mixed $arg0)
* @method UIxFlatButton setPrefSize($mixed)
* @method UIxFlatButton _setPaddingLeft(mixed $arg0)
* @method UIxFlatButton _setPaddingBottom(mixed $arg0)
* @method UIxFlatButton _setPaddingRight(mixed $arg0)
* @method UIxFlatButton setStylesheets($mixed)
* @method UIxFlatButton setChildrenUnmodifiable($mixed)
* @method UIxFlatButton _setCache(mixed $arg0)
* @method UIxFlatButton _setRotate(mixed $arg0)
* @method UIxFlatButton _setId(mixed $arg0)
* @method UIxFlatButton _setOpacity(mixed $arg0)
* @method UIxFlatButton _setStyle(mixed $arg0)
* @method UIxFlatButton setDisabled($mixed)
* @method UIxFlatButton _setVisible(mixed $arg0)
* @method UIxFlatButton _setManaged(mixed $arg0)
* @method UIxFlatButton setPressed($mixed)
* @method UIxFlatButton setFocused($mixed)
* @method UIxFlatButton setHover($mixed)
* @method UIxFlatButton _setPickOnBounds(mixed $arg0)
* @method UIxFlatButton setClasses($mixed)
* @method UIxFlatButton _setBlendMode( $arg0)
* @method UIxFlatButton _setFocusTraversable(mixed $arg0)
* @method UIxFlatButton _setScaleX(mixed $arg0)
* @method UIxFlatButton _setScaleY(mixed $arg0)
* @method UIxFlatButton _setTranslateX(mixed $arg0)
* @method UIxFlatButton _setTranslateY(mixed $arg0)
* @method UIxFlatButton _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxFlatButton setBaselineOffset($mixed)
* @method UIxFlatButton _setClip(php\gui\UXNode $arg0)
* @method UIxFlatButton _setScaleZ(mixed $arg0)
* @method UIxFlatButton _setDepthTest( $arg0)
* @method UIxFlatButton _setTranslateZ(mixed $arg0)
* @method UIxFlatButton _setCacheHint( $arg0)
* @method UIxFlatButton _setMouseTransparent(mixed $arg0)
* @method UIxFlatButton setContentBias($mixed)
* @method UIxFlatButton setParent($mixed)
* @method UIxFlatButton _setSize(array $arg0)
* @method UIxFlatButton setLayoutBounds($mixed)
* @method UIxFlatButton _setWidth(mixed $arg0)
* @method UIxFlatButton setScene($mixed)
* @method UIxFlatButton _setX(mixed $arg0)
* @method UIxFlatButton _setY(mixed $arg0)
* @method UIxFlatButton setBoundsInParent($mixed)
* @method UIxFlatButton _setUserData(mixed $arg0)
* @method UIxFlatButton _setCursor(mixed $arg0)
* @method UIxFlatButton _setScale(mixed $arg0)
* @method UIxFlatButton _setHeight(mixed $arg0)
* @method UIxFlatButton setWindow($mixed)
* @method UIxFlatButton _setPosition(array $arg0)
* @method UIxFlatButton setForm($mixed)
* @method UIxFlatButton _setEnabled(mixed $arg0)
* @method UIxFlatButton _setScreenPosition(array $arg0)
* @method UIxFlatButton _setScreenY(mixed $arg0)
* @method UIxFlatButton _setScreenX(mixed $arg0)
* @method UIxFlatButton _setClassesString(mixed $arg0)
* @method UIxFlatButton _setRightAnchor(mixed $arg0)
* @method UIxFlatButton _setBottomAnchor(mixed $arg0)
* @method UIxFlatButton setEffects($mixed)
* @method UIxFlatButton _setTopAnchor(mixed $arg0)
* @method UIxFlatButton _setAnchorFlags(array $arg0)
* @method UIxFlatButton _setAnchors(array $arg0)
* @method UIxFlatButton _setLeftAnchor(mixed $arg0) */

class UIxFlatButton extends UXFlatButton {
    use Cascadable;
}
