<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXFragmentPane;

/**
* @method UIxFragmentPane setLayout($mixed)
* @method UIxFragmentPane _setSpacing(mixed $arg0)
* @method UIxFragmentPane _setFillWidth(mixed $arg0)
* @method UIxFragmentPane _setAlignment( $arg0)
* @method UIxFragmentPane setChildren($mixed)
* @method UIxFragmentPane _setMinHeight(mixed $arg0)
* @method UIxFragmentPane _setMaxWidth(mixed $arg0)
* @method UIxFragmentPane _setMinWidth(mixed $arg0)
* @method UIxFragmentPane _setMaxHeight(mixed $arg0)
* @method UIxFragmentPane _setPadding(mixed $arg0)
* @method UIxFragmentPane _setMinSize(array $arg0)
* @method UIxFragmentPane _setMaxSize(array $arg0)
* @method UIxFragmentPane _setBackgroundColor(mixed $arg0)
* @method UIxFragmentPane _setPaddingLeft(mixed $arg0)
* @method UIxFragmentPane _setPaddingRight(mixed $arg0)
* @method UIxFragmentPane _setPaddingTop(mixed $arg0)
* @method UIxFragmentPane _setPaddingBottom(mixed $arg0)
* @method UIxFragmentPane setPrefSize($mixed)
* @method UIxFragmentPane setStylesheets($mixed)
* @method UIxFragmentPane setChildrenUnmodifiable($mixed)
* @method UIxFragmentPane _setCache(mixed $arg0)
* @method UIxFragmentPane _setRotate(mixed $arg0)
* @method UIxFragmentPane _setId(mixed $arg0)
* @method UIxFragmentPane _setOpacity(mixed $arg0)
* @method UIxFragmentPane _setManaged(mixed $arg0)
* @method UIxFragmentPane _setVisible(mixed $arg0)
* @method UIxFragmentPane _setStyle(mixed $arg0)
* @method UIxFragmentPane setDisabled($mixed)
* @method UIxFragmentPane setFocused($mixed)
* @method UIxFragmentPane setHover($mixed)
* @method UIxFragmentPane setPressed($mixed)
* @method UIxFragmentPane _setFocusTraversable(mixed $arg0)
* @method UIxFragmentPane _setBlendMode( $arg0)
* @method UIxFragmentPane _setPickOnBounds(mixed $arg0)
* @method UIxFragmentPane setClasses($mixed)
* @method UIxFragmentPane setResizable($mixed)
* @method UIxFragmentPane _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxFragmentPane setBaselineOffset($mixed)
* @method UIxFragmentPane _setClip(php\gui\UXNode $arg0)
* @method UIxFragmentPane _setScaleX(mixed $arg0)
* @method UIxFragmentPane _setScaleY(mixed $arg0)
* @method UIxFragmentPane _setTranslateX(mixed $arg0)
* @method UIxFragmentPane _setTranslateY(mixed $arg0)
* @method UIxFragmentPane _setDepthTest( $arg0)
* @method UIxFragmentPane _setScaleZ(mixed $arg0)
* @method UIxFragmentPane _setTranslateZ(mixed $arg0)
* @method UIxFragmentPane _setCacheHint( $arg0)
* @method UIxFragmentPane _setMouseTransparent(mixed $arg0)
* @method UIxFragmentPane setContentBias($mixed)
* @method UIxFragmentPane setParent($mixed)
* @method UIxFragmentPane _setSize(array $arg0)
* @method UIxFragmentPane setLayoutBounds($mixed)
* @method UIxFragmentPane _setWidth(mixed $arg0)
* @method UIxFragmentPane setScene($mixed)
* @method UIxFragmentPane setBoundsInParent($mixed)
* @method UIxFragmentPane _setX(mixed $arg0)
* @method UIxFragmentPane _setY(mixed $arg0)
* @method UIxFragmentPane _setUserData(mixed $arg0)
* @method UIxFragmentPane _setCursor(mixed $arg0)
* @method UIxFragmentPane _setScale(mixed $arg0)
* @method UIxFragmentPane _setHeight(mixed $arg0)
* @method UIxFragmentPane setWindow($mixed)
* @method UIxFragmentPane _setPosition(array $arg0)
* @method UIxFragmentPane setForm($mixed)
* @method UIxFragmentPane _setEnabled(mixed $arg0)
* @method UIxFragmentPane _setScreenPosition(array $arg0)
* @method UIxFragmentPane _setScreenX(mixed $arg0)
* @method UIxFragmentPane _setScreenY(mixed $arg0)
* @method UIxFragmentPane _setAnchors(array $arg0)
* @method UIxFragmentPane _setRightAnchor(mixed $arg0)
* @method UIxFragmentPane _setClassesString(mixed $arg0)
* @method UIxFragmentPane _setTopAnchor(mixed $arg0)
* @method UIxFragmentPane _setAnchorFlags(array $arg0)
* @method UIxFragmentPane setEffects($mixed)
* @method UIxFragmentPane _setLeftAnchor(mixed $arg0)
* @method UIxFragmentPane _setBottomAnchor(mixed $arg0) */

class UIxFragmentPane extends UXFragmentPane {
    use Cascadable;
}
