<?php 

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\layout\UXHBox;

/**
* @method UIxHBox _setSpacing(mixed $arg0)
* @method UIxHBox _setAlignment( $arg0)
* @method UIxHBox _setFillHeight(mixed $arg0)
* @method UIxHBox setChildren($mixed)
* @method UIxHBox _setMinHeight(mixed $arg0)
* @method UIxHBox _setMinWidth(mixed $arg0)
* @method UIxHBox _setMaxWidth(mixed $arg0)
* @method UIxHBox _setMaxHeight(mixed $arg0)
* @method UIxHBox _setPadding(mixed $arg0)
* @method UIxHBox _setMaxSize(array $arg0)
* @method UIxHBox _setMinSize(array $arg0)
* @method UIxHBox _setBackgroundColor(mixed $arg0)
* @method UIxHBox setPrefSize($mixed)
* @method UIxHBox _setPaddingRight(mixed $arg0)
* @method UIxHBox _setPaddingLeft(mixed $arg0)
* @method UIxHBox _setPaddingTop(mixed $arg0)
* @method UIxHBox _setPaddingBottom(mixed $arg0)
* @method UIxHBox setStylesheets($mixed)
* @method UIxHBox setChildrenUnmodifiable($mixed)
* @method UIxHBox _setCache(mixed $arg0)
* @method UIxHBox _setRotate(mixed $arg0)
* @method UIxHBox _setId(mixed $arg0)
* @method UIxHBox _setOpacity(mixed $arg0)
* @method UIxHBox _setStyle(mixed $arg0)
* @method UIxHBox _setManaged(mixed $arg0)
* @method UIxHBox setDisabled($mixed)
* @method UIxHBox _setVisible(mixed $arg0)
* @method UIxHBox setHover($mixed)
* @method UIxHBox setPressed($mixed)
* @method UIxHBox setFocused($mixed)
* @method UIxHBox _setPickOnBounds(mixed $arg0)
* @method UIxHBox _setBlendMode( $arg0)
* @method UIxHBox setClasses($mixed)
* @method UIxHBox _setFocusTraversable(mixed $arg0)
* @method UIxHBox setResizable($mixed)
* @method UIxHBox _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxHBox setBaselineOffset($mixed)
* @method UIxHBox _setScaleX(mixed $arg0)
* @method UIxHBox _setScaleY(mixed $arg0)
* @method UIxHBox _setTranslateX(mixed $arg0)
* @method UIxHBox _setTranslateY(mixed $arg0)
* @method UIxHBox _setClip(php\gui\UXNode $arg0)
* @method UIxHBox _setDepthTest( $arg0)
* @method UIxHBox _setScaleZ(mixed $arg0)
* @method UIxHBox _setMouseTransparent(mixed $arg0)
* @method UIxHBox _setCacheHint( $arg0)
* @method UIxHBox _setTranslateZ(mixed $arg0)
* @method UIxHBox setContentBias($mixed)
* @method UIxHBox setParent($mixed)
* @method UIxHBox _setSize(array $arg0)
* @method UIxHBox setLayoutBounds($mixed)
* @method UIxHBox _setWidth(mixed $arg0)
* @method UIxHBox setScene($mixed)
* @method UIxHBox setBoundsInParent($mixed)
* @method UIxHBox _setCursor(mixed $arg0)
* @method UIxHBox _setUserData(mixed $arg0)
* @method UIxHBox _setScale(mixed $arg0)
* @method UIxHBox _setPosition(array $arg0)
* @method UIxHBox _setY(mixed $arg0)
* @method UIxHBox _setX(mixed $arg0)
* @method UIxHBox _setHeight(mixed $arg0)
* @method UIxHBox setWindow($mixed)
* @method UIxHBox _setEnabled(mixed $arg0)
* @method UIxHBox setForm($mixed)
* @method UIxHBox _setScreenPosition(array $arg0)
* @method UIxHBox _setScreenX(mixed $arg0)
* @method UIxHBox _setScreenY(mixed $arg0)
* @method UIxHBox _setClassesString(mixed $arg0)
* @method UIxHBox _setAnchors(array $arg0)
* @method UIxHBox _setTopAnchor(mixed $arg0)
* @method UIxHBox _setLeftAnchor(mixed $arg0)
* @method UIxHBox setEffects($mixed)
* @method UIxHBox _setRightAnchor(mixed $arg0)
* @method UIxHBox _setAnchorFlags(array $arg0)
* @method UIxHBox _setBottomAnchor(mixed $arg0)
*/

class UIxHBox extends UXHBox
{
    use Cascadable;


    
}