<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXHyperlink;

/**
* @method UIxHyperlink _setVisited(mixed $arg0)
* @method UIxHyperlink setArmed($mixed)
* @method UIxHyperlink _setText(mixed $arg0)
* @method UIxHyperlink _setAlignment( $arg0)
* @method UIxHyperlink _setWrapText(mixed $arg0)
* @method UIxHyperlink _setTextAlignment( $arg0)
* @method UIxHyperlink _setContentDisplay( $arg0)
* @method UIxHyperlink _setGraphicTextGap(mixed $arg0)
* @method UIxHyperlink _setMnemonicParsing(mixed $arg0)
* @method UIxHyperlink _setUnderline(mixed $arg0)
* @method UIxHyperlink _setEllipsisString(mixed $arg0)
* @method UIxHyperlink _setFont(php\gui\text\UXFont $arg0)
* @method UIxHyperlink _setGraphic(php\gui\UXNode $arg0)
* @method UIxHyperlink _setTextColor(mixed $arg0)
* @method UIxHyperlink setResizable($mixed)
* @method UIxHyperlink _setTooltip(php\gui\UXTooltip $arg0)
* @method UIxHyperlink _setContextMenu(php\gui\UXContextMenu $arg0)
* @method UIxHyperlink _setTooltipText(mixed $arg0)
* @method UIxHyperlink _setMinHeight(mixed $arg0)
* @method UIxHyperlink _setMinWidth(mixed $arg0)
* @method UIxHyperlink _setMaxWidth(mixed $arg0)
* @method UIxHyperlink _setMaxHeight(mixed $arg0)
* @method UIxHyperlink _setPadding(mixed $arg0)
* @method UIxHyperlink _setMaxSize(array $arg0)
* @method UIxHyperlink _setMinSize(array $arg0)
* @method UIxHyperlink _setBackgroundColor(mixed $arg0)
* @method UIxHyperlink _setPaddingRight(mixed $arg0)
* @method UIxHyperlink _setPaddingTop(mixed $arg0)
* @method UIxHyperlink _setPaddingLeft(mixed $arg0)
* @method UIxHyperlink _setPaddingBottom(mixed $arg0)
* @method UIxHyperlink setPrefSize($mixed)
* @method UIxHyperlink setStylesheets($mixed)
* @method UIxHyperlink setChildrenUnmodifiable($mixed)
* @method UIxHyperlink _setCache(mixed $arg0)
* @method UIxHyperlink _setRotate(mixed $arg0)
* @method UIxHyperlink _setId(mixed $arg0)
* @method UIxHyperlink _setOpacity(mixed $arg0)
* @method UIxHyperlink _setStyle(mixed $arg0)
* @method UIxHyperlink _setVisible(mixed $arg0)
* @method UIxHyperlink _setManaged(mixed $arg0)
* @method UIxHyperlink setDisabled($mixed)
* @method UIxHyperlink setPressed($mixed)
* @method UIxHyperlink setFocused($mixed)
* @method UIxHyperlink setHover($mixed)
* @method UIxHyperlink setClasses($mixed)
* @method UIxHyperlink _setPickOnBounds(mixed $arg0)
* @method UIxHyperlink _setBlendMode( $arg0)
* @method UIxHyperlink _setFocusTraversable(mixed $arg0)
* @method UIxHyperlink _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxHyperlink setBaselineOffset($mixed)
* @method UIxHyperlink _setClip(php\gui\UXNode $arg0)
* @method UIxHyperlink _setScaleX(mixed $arg0)
* @method UIxHyperlink _setScaleY(mixed $arg0)
* @method UIxHyperlink _setTranslateX(mixed $arg0)
* @method UIxHyperlink _setTranslateY(mixed $arg0)
* @method UIxHyperlink _setDepthTest( $arg0)
* @method UIxHyperlink _setScaleZ(mixed $arg0)
* @method UIxHyperlink _setMouseTransparent(mixed $arg0)
* @method UIxHyperlink _setCacheHint( $arg0)
* @method UIxHyperlink _setTranslateZ(mixed $arg0)
* @method UIxHyperlink setContentBias($mixed)
* @method UIxHyperlink setParent($mixed)
* @method UIxHyperlink _setSize(array $arg0)
* @method UIxHyperlink setLayoutBounds($mixed)
* @method UIxHyperlink _setWidth(mixed $arg0)
* @method UIxHyperlink setScene($mixed)
* @method UIxHyperlink _setX(mixed $arg0)
* @method UIxHyperlink _setY(mixed $arg0)
* @method UIxHyperlink setBoundsInParent($mixed)
* @method UIxHyperlink _setCursor(mixed $arg0)
* @method UIxHyperlink _setUserData(mixed $arg0)
* @method UIxHyperlink _setPosition(array $arg0)
* @method UIxHyperlink _setScale(mixed $arg0)
* @method UIxHyperlink _setHeight(mixed $arg0)
* @method UIxHyperlink setWindow($mixed)
* @method UIxHyperlink setForm($mixed)
* @method UIxHyperlink _setEnabled(mixed $arg0)
* @method UIxHyperlink _setScreenPosition(array $arg0)
* @method UIxHyperlink _setScreenY(mixed $arg0)
* @method UIxHyperlink _setScreenX(mixed $arg0)
* @method UIxHyperlink _setAnchorFlags(array $arg0)
* @method UIxHyperlink _setRightAnchor(mixed $arg0)
* @method UIxHyperlink _setBottomAnchor(mixed $arg0)
* @method UIxHyperlink _setLeftAnchor(mixed $arg0)
* @method UIxHyperlink _setAnchors(array $arg0)
* @method UIxHyperlink _setClassesString(mixed $arg0)
* @method UIxHyperlink setEffects($mixed)
* @method UIxHyperlink _setTopAnchor(mixed $arg0) */

class UIxHyperlink extends UXHyperlink {
    use Cascadable;
}
