<?php 

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXListView;
/**
* @method UIxListView _setItems(php\gui\UXList $arg0)
* @method UIxListView _setEditable(mixed $arg0)
* @method UIxListView _setOrientation( $arg0)
* @method UIxListView _setPlaceholder(php\gui\UXNode $arg0)
* @method UIxListView _setFixedCellSize(mixed $arg0)
* @method UIxListView setEditingIndex($mixed)
* @method UIxListView _setItemsText(mixed $arg0)
* @method UIxListView _setSelectedIndex(mixed $arg0)
* @method UIxListView setSelectedItem($mixed)
* @method UIxListView setSelectedItems($mixed)
* @method UIxListView setFocusedItem($mixed)
* @method UIxListView _setFocusedIndex(mixed $arg0)
* @method UIxListView _setMultipleSelection(mixed $arg0)
* @method UIxListView _setSelectedIndexes(array $arg0)
* @method UIxListView setResizable($mixed)
* @method UIxListView _setTooltip(php\gui\UXTooltip $arg0)
* @method UIxListView _setContextMenu(php\gui\UXContextMenu $arg0)
* @method UIxListView _setTooltipText(mixed $arg0)
* @method UIxListView _setMinWidth(mixed $arg0)
* @method UIxListView _setMaxWidth(mixed $arg0)
* @method UIxListView _setMinHeight(mixed $arg0)
* @method UIxListView _setMaxHeight(mixed $arg0)
* @method UIxListView _setPadding(mixed $arg0)
* @method UIxListView _setMinSize(array $arg0)
* @method UIxListView _setMaxSize(array $arg0)
* @method UIxListView _setBackgroundColor(mixed $arg0)
* @method UIxListView setPrefSize($mixed)
* @method UIxListView _setPaddingLeft(mixed $arg0)
* @method UIxListView _setPaddingTop(mixed $arg0)
* @method UIxListView _setPaddingBottom(mixed $arg0)
* @method UIxListView _setPaddingRight(mixed $arg0)
* @method UIxListView setStylesheets($mixed)
* @method UIxListView setChildrenUnmodifiable($mixed)
* @method UIxListView _setCache(mixed $arg0)
* @method UIxListView _setRotate(mixed $arg0)
* @method UIxListView _setId(mixed $arg0)
* @method UIxListView _setOpacity(mixed $arg0)
* @method UIxListView _setStyle(mixed $arg0)
* @method UIxListView _setVisible(mixed $arg0)
* @method UIxListView setDisabled($mixed)
* @method UIxListView _setManaged(mixed $arg0)
* @method UIxListView setFocused($mixed)
* @method UIxListView setHover($mixed)
* @method UIxListView setPressed($mixed)
* @method UIxListView _setFocusTraversable(mixed $arg0)
* @method UIxListView setClasses($mixed)
* @method UIxListView _setBlendMode( $arg0)
* @method UIxListView _setPickOnBounds(mixed $arg0)
* @method UIxListView _setScaleX(mixed $arg0)
* @method UIxListView _setScaleY(mixed $arg0)
* @method UIxListView _setTranslateX(mixed $arg0)
* @method UIxListView _setTranslateY(mixed $arg0)
* @method UIxListView _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxListView setBaselineOffset($mixed)
* @method UIxListView _setClip(php\gui\UXNode $arg0)
* @method UIxListView _setDepthTest( $arg0)
* @method UIxListView _setScaleZ(mixed $arg0)
* @method UIxListView _setTranslateZ(mixed $arg0)
* @method UIxListView _setCacheHint( $arg0)
* @method UIxListView _setMouseTransparent(mixed $arg0)
* @method UIxListView setContentBias($mixed)
* @method UIxListView setParent($mixed)
* @method UIxListView _setSize(array $arg0)
* @method UIxListView _setWidth(mixed $arg0)
* @method UIxListView setScene($mixed)
* @method UIxListView setLayoutBounds($mixed)
* @method UIxListView _setY(mixed $arg0)
* @method UIxListView _setX(mixed $arg0)
* @method UIxListView setBoundsInParent($mixed)
* @method UIxListView _setUserData(mixed $arg0)
* @method UIxListView _setCursor(mixed $arg0)
* @method UIxListView _setPosition(array $arg0)
* @method UIxListView _setScale(mixed $arg0)
* @method UIxListView _setHeight(mixed $arg0)
* @method UIxListView setWindow($mixed)
* @method UIxListView setForm($mixed)
* @method UIxListView _setEnabled(mixed $arg0)
* @method UIxListView _setScreenPosition(array $arg0)
* @method UIxListView _setScreenX(mixed $arg0)
* @method UIxListView _setScreenY(mixed $arg0)
* @method UIxListView _setClassesString(mixed $arg0)
* @method UIxListView _setRightAnchor(mixed $arg0)
* @method UIxListView _setTopAnchor(mixed $arg0)
* @method UIxListView setEffects($mixed)
* @method UIxListView _setAnchors(array $arg0)
* @method UIxListView _setBottomAnchor(mixed $arg0)
* @method UIxListView _setAnchorFlags(array $arg0)
* @method UIxListView _setLeftAnchor(mixed $arg0)
 */
class UIxListView extends UXListView
{
    use Cascadable;


    
}