<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXMediaViewBox;

/**
* @method UIxMediaViewBox _setSmooth(mixed $arg0)
* @method UIxMediaViewBox _setProportional(mixed $arg0)
* @method UIxMediaViewBox setPlayer($mixed)
* @method UIxMediaViewBox _setTitle(mixed $arg0)
* @method UIxMediaViewBox _setBorderColor(mixed $arg0)
* @method UIxMediaViewBox _setBorderStyle(mixed $arg0)
* @method UIxMediaViewBox _setBorderRadius(mixed $arg0)
* @method UIxMediaViewBox _setTitleOffset(mixed $arg0)
* @method UIxMediaViewBox _setTitlePosition( $arg0)
* @method UIxMediaViewBox _setBorderWidth(mixed $arg0)
* @method UIxMediaViewBox _setTitleColor(mixed $arg0)
* @method UIxMediaViewBox _setTitleFont(php\gui\text\UXFont $arg0)
* @method UIxMediaViewBox _setBackgroundColor(mixed $arg0)
* @method UIxMediaViewBox setChildren($mixed)
* @method UIxMediaViewBox _setMinHeight(mixed $arg0)
* @method UIxMediaViewBox _setMinWidth(mixed $arg0)
* @method UIxMediaViewBox _setMaxWidth(mixed $arg0)
* @method UIxMediaViewBox _setMaxHeight(mixed $arg0)
* @method UIxMediaViewBox _setPadding(mixed $arg0)
* @method UIxMediaViewBox _setMinSize(array $arg0)
* @method UIxMediaViewBox _setMaxSize(array $arg0)
* @method UIxMediaViewBox _setPaddingTop(mixed $arg0)
* @method UIxMediaViewBox _setPaddingBottom(mixed $arg0)
* @method UIxMediaViewBox _setPaddingRight(mixed $arg0)
* @method UIxMediaViewBox setPrefSize($mixed)
* @method UIxMediaViewBox _setPaddingLeft(mixed $arg0)
* @method UIxMediaViewBox setStylesheets($mixed)
* @method UIxMediaViewBox setChildrenUnmodifiable($mixed)
* @method UIxMediaViewBox _setCache(mixed $arg0)
* @method UIxMediaViewBox _setRotate(mixed $arg0)
* @method UIxMediaViewBox _setId(mixed $arg0)
* @method UIxMediaViewBox _setOpacity(mixed $arg0)
* @method UIxMediaViewBox _setStyle(mixed $arg0)
* @method UIxMediaViewBox _setVisible(mixed $arg0)
* @method UIxMediaViewBox setDisabled($mixed)
* @method UIxMediaViewBox _setPickOnBounds(mixed $arg0)
* @method UIxMediaViewBox _setBlendMode( $arg0)
* @method UIxMediaViewBox setClasses($mixed)
* @method UIxMediaViewBox _setFocusTraversable(mixed $arg0)
* @method UIxMediaViewBox setHover($mixed)
* @method UIxMediaViewBox setFocused($mixed)
* @method UIxMediaViewBox setPressed($mixed)
* @method UIxMediaViewBox _setManaged(mixed $arg0)
* @method UIxMediaViewBox setResizable($mixed)
* @method UIxMediaViewBox _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxMediaViewBox setBaselineOffset($mixed)
* @method UIxMediaViewBox _setScaleX(mixed $arg0)
* @method UIxMediaViewBox _setScaleY(mixed $arg0)
* @method UIxMediaViewBox _setTranslateX(mixed $arg0)
* @method UIxMediaViewBox _setTranslateY(mixed $arg0)
* @method UIxMediaViewBox _setClip(php\gui\UXNode $arg0)
* @method UIxMediaViewBox _setDepthTest( $arg0)
* @method UIxMediaViewBox _setScaleZ(mixed $arg0)
* @method UIxMediaViewBox _setTranslateZ(mixed $arg0)
* @method UIxMediaViewBox _setCacheHint( $arg0)
* @method UIxMediaViewBox _setMouseTransparent(mixed $arg0)
* @method UIxMediaViewBox setContentBias($mixed)
* @method UIxMediaViewBox setParent($mixed)
* @method UIxMediaViewBox _setSize(array $arg0)
* @method UIxMediaViewBox setLayoutBounds($mixed)
* @method UIxMediaViewBox setBoundsInParent($mixed)
* @method UIxMediaViewBox _setCursor(mixed $arg0)
* @method UIxMediaViewBox _setUserData(mixed $arg0)
* @method UIxMediaViewBox _setWidth(mixed $arg0)
* @method UIxMediaViewBox _setX(mixed $arg0)
* @method UIxMediaViewBox _setY(mixed $arg0)
* @method UIxMediaViewBox _setPosition(array $arg0)
* @method UIxMediaViewBox _setScale(mixed $arg0)
* @method UIxMediaViewBox setScene($mixed)
* @method UIxMediaViewBox _setHeight(mixed $arg0)
* @method UIxMediaViewBox setWindow($mixed)
* @method UIxMediaViewBox setForm($mixed)
* @method UIxMediaViewBox _setEnabled(mixed $arg0)
* @method UIxMediaViewBox _setScreenPosition(array $arg0)
* @method UIxMediaViewBox _setScreenX(mixed $arg0)
* @method UIxMediaViewBox _setScreenY(mixed $arg0)
* @method UIxMediaViewBox _setAnchorFlags(array $arg0)
* @method UIxMediaViewBox _setTopAnchor(php\gui\UXNode $arg0, mixed $arg1)
* @method UIxMediaViewBox _setRightAnchor(php\gui\UXNode $arg0, mixed $arg1)
* @method UIxMediaViewBox _setBottomAnchor(php\gui\UXNode $arg0, mixed $arg1)
* @method UIxMediaViewBox _setAnchors(array $arg0)
* @method UIxMediaViewBox _setLeftAnchor(php\gui\UXNode $arg0, mixed $arg1)
* @method UIxMediaViewBox _setClassesString(mixed $arg0)
* @method UIxMediaViewBox setEffects($mixed) */

class UIxMediaViewBox extends UXMediaViewBox {
    use Cascadable;
}
