<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXMaskTextField;

/**
* @method UIxMaskTextField _setMask(mixed $arg0)
* @method UIxMaskTextField _setWhatMask(mixed $arg0)
* @method UIxMaskTextField _setPlaceholder(mixed $arg0)
* @method UIxMaskTextField _setPlainText(mixed $arg0)
* @method UIxMaskTextField _setAlignment( $arg0)
* @method UIxMaskTextField _setPrefColumnCount(mixed $arg0)
* @method UIxMaskTextField setLength($mixed)
* @method UIxMaskTextField _setText(mixed $arg0)
* @method UIxMaskTextField setAnchor($mixed)
* @method UIxMaskTextField _setEditable(mixed $arg0)
* @method UIxMaskTextField _setSelectedText(mixed $arg0)
* @method UIxMaskTextField setCaretPosition($mixed)
* @method UIxMaskTextField _setPromptText(mixed $arg0)
* @method UIxMaskTextField _setFont(php\gui\text\UXFont $arg0)
* @method UIxMaskTextField setSelection($mixed)
* @method UIxMaskTextField setResizable($mixed)
* @method UIxMaskTextField _setTooltip(php\gui\UXTooltip $arg0)
* @method UIxMaskTextField _setContextMenu(php\gui\UXContextMenu $arg0)
* @method UIxMaskTextField _setTooltipText(mixed $arg0)
* @method UIxMaskTextField _setMinHeight(mixed $arg0)
* @method UIxMaskTextField _setMinWidth(mixed $arg0)
* @method UIxMaskTextField _setMaxWidth(mixed $arg0)
* @method UIxMaskTextField _setMaxHeight(mixed $arg0)
* @method UIxMaskTextField _setPadding(mixed $arg0)
* @method UIxMaskTextField _setMaxSize(array $arg0)
* @method UIxMaskTextField _setMinSize(array $arg0)
* @method UIxMaskTextField _setBackgroundColor(mixed $arg0)
* @method UIxMaskTextField _setPaddingRight(mixed $arg0)
* @method UIxMaskTextField _setPaddingBottom(mixed $arg0)
* @method UIxMaskTextField _setPaddingTop(mixed $arg0)
* @method UIxMaskTextField _setPaddingLeft(mixed $arg0)
* @method UIxMaskTextField setPrefSize($mixed)
* @method UIxMaskTextField setStylesheets($mixed)
* @method UIxMaskTextField setChildrenUnmodifiable($mixed)
* @method UIxMaskTextField _setCache(mixed $arg0)
* @method UIxMaskTextField _setRotate(mixed $arg0)
* @method UIxMaskTextField _setId(mixed $arg0)
* @method UIxMaskTextField _setOpacity(mixed $arg0)
* @method UIxMaskTextField _setManaged(mixed $arg0)
* @method UIxMaskTextField _setVisible(mixed $arg0)
* @method UIxMaskTextField _setStyle(mixed $arg0)
* @method UIxMaskTextField setFocused($mixed)
* @method UIxMaskTextField setHover($mixed)
* @method UIxMaskTextField setDisabled($mixed)
* @method UIxMaskTextField setPressed($mixed)
* @method UIxMaskTextField _setFocusTraversable(mixed $arg0)
* @method UIxMaskTextField setClasses($mixed)
* @method UIxMaskTextField _setBlendMode( $arg0)
* @method UIxMaskTextField _setPickOnBounds(mixed $arg0)
* @method UIxMaskTextField _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxMaskTextField setBaselineOffset($mixed)
* @method UIxMaskTextField _setScaleX(mixed $arg0)
* @method UIxMaskTextField _setScaleY(mixed $arg0)
* @method UIxMaskTextField _setTranslateX(mixed $arg0)
* @method UIxMaskTextField _setTranslateY(mixed $arg0)
* @method UIxMaskTextField _setClip(php\gui\UXNode $arg0)
* @method UIxMaskTextField _setDepthTest( $arg0)
* @method UIxMaskTextField _setScaleZ(mixed $arg0)
* @method UIxMaskTextField _setCacheHint( $arg0)
* @method UIxMaskTextField _setTranslateZ(mixed $arg0)
* @method UIxMaskTextField _setMouseTransparent(mixed $arg0)
* @method UIxMaskTextField setContentBias($mixed)
* @method UIxMaskTextField setParent($mixed)
* @method UIxMaskTextField _setSize(array $arg0)
* @method UIxMaskTextField setLayoutBounds($mixed)
* @method UIxMaskTextField _setWidth(mixed $arg0)
* @method UIxMaskTextField setScene($mixed)
* @method UIxMaskTextField _setX(mixed $arg0)
* @method UIxMaskTextField _setY(mixed $arg0)
* @method UIxMaskTextField setBoundsInParent($mixed)
* @method UIxMaskTextField _setUserData(mixed $arg0)
* @method UIxMaskTextField _setCursor(mixed $arg0)
* @method UIxMaskTextField _setPosition(array $arg0)
* @method UIxMaskTextField _setScale(mixed $arg0)
* @method UIxMaskTextField _setHeight(mixed $arg0)
* @method UIxMaskTextField setWindow($mixed)
* @method UIxMaskTextField setForm($mixed)
* @method UIxMaskTextField _setEnabled(mixed $arg0)
* @method UIxMaskTextField _setScreenPosition(array $arg0)
* @method UIxMaskTextField _setScreenY(mixed $arg0)
* @method UIxMaskTextField _setScreenX(mixed $arg0)
* @method UIxMaskTextField _setAnchors(array $arg0)
* @method UIxMaskTextField _setBottomAnchor(mixed $arg0)
* @method UIxMaskTextField _setClassesString(mixed $arg0)
* @method UIxMaskTextField _setLeftAnchor(mixed $arg0)
* @method UIxMaskTextField _setRightAnchor(mixed $arg0)
* @method UIxMaskTextField _setTopAnchor(mixed $arg0)
* @method UIxMaskTextField _setAnchorFlags(array $arg0)
* @method UIxMaskTextField setEffects($mixed) */

class UIxMaskTextField extends UXMaskTextField {
    use Cascadable;
}
