<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXNumberSpinner;

/**
* @method UIxNumberSpinner _setMin(mixed $arg0)
* @method UIxNumberSpinner _setMax(mixed $arg0)
* @method UIxNumberSpinner _setStep(mixed $arg0)
* @method UIxNumberSpinner _setInitial(mixed $arg0)
* @method UIxNumberSpinner _setArrowsStyle( $arg0)
* @method UIxNumberSpinner _setValue(mixed $arg0)
* @method UIxNumberSpinner _setAlignment( $arg0)
* @method UIxNumberSpinner setEditor($mixed)
* @method UIxNumberSpinner _setEditable(mixed $arg0)
* @method UIxNumberSpinner setResizable($mixed)
* @method UIxNumberSpinner _setTooltip(php\gui\UXTooltip $arg0)
* @method UIxNumberSpinner _setContextMenu(php\gui\UXContextMenu $arg0)
* @method UIxNumberSpinner _setTooltipText(mixed $arg0)
* @method UIxNumberSpinner _setMinWidth(mixed $arg0)
* @method UIxNumberSpinner _setMaxWidth(mixed $arg0)
* @method UIxNumberSpinner _setMinHeight(mixed $arg0)
* @method UIxNumberSpinner _setMaxHeight(mixed $arg0)
* @method UIxNumberSpinner _setPadding(mixed $arg0)
* @method UIxNumberSpinner _setMaxSize(array $arg0)
* @method UIxNumberSpinner _setMinSize(array $arg0)
* @method UIxNumberSpinner _setBackgroundColor(mixed $arg0)
* @method UIxNumberSpinner _setPaddingRight(mixed $arg0)
* @method UIxNumberSpinner _setPaddingTop(mixed $arg0)
* @method UIxNumberSpinner _setPaddingLeft(mixed $arg0)
* @method UIxNumberSpinner _setPaddingBottom(mixed $arg0)
* @method UIxNumberSpinner setPrefSize($mixed)
* @method UIxNumberSpinner setStylesheets($mixed)
* @method UIxNumberSpinner setChildrenUnmodifiable($mixed)
* @method UIxNumberSpinner _setCache(mixed $arg0)
* @method UIxNumberSpinner _setRotate(mixed $arg0)
* @method UIxNumberSpinner _setId(mixed $arg0)
* @method UIxNumberSpinner _setScaleX(mixed $arg0)
* @method UIxNumberSpinner _setScaleY(mixed $arg0)
* @method UIxNumberSpinner _setTranslateX(mixed $arg0)
* @method UIxNumberSpinner _setTranslateY(mixed $arg0)
* @method UIxNumberSpinner _setOpacity(mixed $arg0)
* @method UIxNumberSpinner _setStyle(mixed $arg0)
* @method UIxNumberSpinner _setVisible(mixed $arg0)
* @method UIxNumberSpinner setDisabled($mixed)
* @method UIxNumberSpinner _setManaged(mixed $arg0)
* @method UIxNumberSpinner setPressed($mixed)
* @method UIxNumberSpinner setHover($mixed)
* @method UIxNumberSpinner setFocused($mixed)
* @method UIxNumberSpinner setClasses($mixed)
* @method UIxNumberSpinner _setPickOnBounds(mixed $arg0)
* @method UIxNumberSpinner _setBlendMode( $arg0)
* @method UIxNumberSpinner _setFocusTraversable(mixed $arg0)
* @method UIxNumberSpinner _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxNumberSpinner setBaselineOffset($mixed)
* @method UIxNumberSpinner _setClip(php\gui\UXNode $arg0)
* @method UIxNumberSpinner _setDepthTest( $arg0)
* @method UIxNumberSpinner _setTranslateZ(mixed $arg0)
* @method UIxNumberSpinner _setCacheHint( $arg0)
* @method UIxNumberSpinner _setMouseTransparent(mixed $arg0)
* @method UIxNumberSpinner setContentBias($mixed)
* @method UIxNumberSpinner _setScaleZ(mixed $arg0)
* @method UIxNumberSpinner setParent($mixed)
* @method UIxNumberSpinner _setSize(array $arg0)
* @method UIxNumberSpinner _setWidth(mixed $arg0)
* @method UIxNumberSpinner setScene($mixed)
* @method UIxNumberSpinner setLayoutBounds($mixed)
* @method UIxNumberSpinner _setX(mixed $arg0)
* @method UIxNumberSpinner _setY(mixed $arg0)
* @method UIxNumberSpinner setBoundsInParent($mixed)
* @method UIxNumberSpinner _setUserData(mixed $arg0)
* @method UIxNumberSpinner _setCursor(mixed $arg0)
* @method UIxNumberSpinner _setPosition(array $arg0)
* @method UIxNumberSpinner _setScale(mixed $arg0)
* @method UIxNumberSpinner _setHeight(mixed $arg0)
* @method UIxNumberSpinner setWindow($mixed)
* @method UIxNumberSpinner _setEnabled(mixed $arg0)
* @method UIxNumberSpinner setForm($mixed)
* @method UIxNumberSpinner _setScreenPosition(array $arg0)
* @method UIxNumberSpinner _setScreenX(mixed $arg0)
* @method UIxNumberSpinner _setScreenY(mixed $arg0)
* @method UIxNumberSpinner setEffects($mixed)
* @method UIxNumberSpinner _setClassesString(mixed $arg0)
* @method UIxNumberSpinner _setLeftAnchor(mixed $arg0)
* @method UIxNumberSpinner _setBottomAnchor(mixed $arg0)
* @method UIxNumberSpinner _setAnchors(array $arg0)
* @method UIxNumberSpinner _setAnchorFlags(array $arg0)
* @method UIxNumberSpinner _setRightAnchor(mixed $arg0)
* @method UIxNumberSpinner _setTopAnchor(mixed $arg0) */

class UIxNumberSpinner extends UXNumberSpinner {
    use Cascadable;
}
