<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXPasswordField;

/**
* @method UIxPasswordField _setAlignment( $arg0)
* @method UIxPasswordField _setPrefColumnCount(mixed $arg0)
* @method UIxPasswordField setLength($mixed)
* @method UIxPasswordField _setText(mixed $arg0)
* @method UIxPasswordField setAnchor($mixed)
* @method UIxPasswordField _setEditable(mixed $arg0)
* @method UIxPasswordField setCaretPosition($mixed)
* @method UIxPasswordField _setSelectedText(mixed $arg0)
* @method UIxPasswordField _setPromptText(mixed $arg0)
* @method UIxPasswordField _setFont(php\gui\text\UXFont $arg0)
* @method UIxPasswordField setSelection($mixed)
* @method UIxPasswordField setResizable($mixed)
* @method UIxPasswordField _setTooltip(php\gui\UXTooltip $arg0)
* @method UIxPasswordField _setContextMenu(php\gui\UXContextMenu $arg0)
* @method UIxPasswordField _setTooltipText(mixed $arg0)
* @method UIxPasswordField _setMinHeight(mixed $arg0)
* @method UIxPasswordField _setMaxWidth(mixed $arg0)
* @method UIxPasswordField _setMinWidth(mixed $arg0)
* @method UIxPasswordField _setMaxHeight(mixed $arg0)
* @method UIxPasswordField _setPadding(mixed $arg0)
* @method UIxPasswordField _setMinSize(array $arg0)
* @method UIxPasswordField _setMaxSize(array $arg0)
* @method UIxPasswordField _setBackgroundColor(mixed $arg0)
* @method UIxPasswordField _setPaddingLeft(mixed $arg0)
* @method UIxPasswordField _setPaddingBottom(mixed $arg0)
* @method UIxPasswordField _setPaddingTop(mixed $arg0)
* @method UIxPasswordField setPrefSize($mixed)
* @method UIxPasswordField _setPaddingRight(mixed $arg0)
* @method UIxPasswordField setStylesheets($mixed)
* @method UIxPasswordField setChildrenUnmodifiable($mixed)
* @method UIxPasswordField _setCache(mixed $arg0)
* @method UIxPasswordField _setRotate(mixed $arg0)
* @method UIxPasswordField _setId(mixed $arg0)
* @method UIxPasswordField _setOpacity(mixed $arg0)
* @method UIxPasswordField setDisabled($mixed)
* @method UIxPasswordField setPressed($mixed)
* @method UIxPasswordField _setVisible(mixed $arg0)
* @method UIxPasswordField _setManaged(mixed $arg0)
* @method UIxPasswordField setHover($mixed)
* @method UIxPasswordField _setStyle(mixed $arg0)
* @method UIxPasswordField setFocused($mixed)
* @method UIxPasswordField _setBlendMode( $arg0)
* @method UIxPasswordField _setPickOnBounds(mixed $arg0)
* @method UIxPasswordField setClasses($mixed)
* @method UIxPasswordField _setFocusTraversable(mixed $arg0)
* @method UIxPasswordField _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxPasswordField setBaselineOffset($mixed)
* @method UIxPasswordField _setClip(php\gui\UXNode $arg0)
* @method UIxPasswordField _setScaleX(mixed $arg0)
* @method UIxPasswordField _setScaleY(mixed $arg0)
* @method UIxPasswordField _setTranslateX(mixed $arg0)
* @method UIxPasswordField _setTranslateY(mixed $arg0)
* @method UIxPasswordField _setDepthTest( $arg0)
* @method UIxPasswordField _setScaleZ(mixed $arg0)
* @method UIxPasswordField _setTranslateZ(mixed $arg0)
* @method UIxPasswordField _setMouseTransparent(mixed $arg0)
* @method UIxPasswordField _setCacheHint( $arg0)
* @method UIxPasswordField setContentBias($mixed)
* @method UIxPasswordField setParent($mixed)
* @method UIxPasswordField _setSize(array $arg0)
* @method UIxPasswordField setLayoutBounds($mixed)
* @method UIxPasswordField _setWidth(mixed $arg0)
* @method UIxPasswordField setScene($mixed)
* @method UIxPasswordField setBoundsInParent($mixed)
* @method UIxPasswordField _setX(mixed $arg0)
* @method UIxPasswordField _setY(mixed $arg0)
* @method UIxPasswordField _setCursor(mixed $arg0)
* @method UIxPasswordField _setUserData(mixed $arg0)
* @method UIxPasswordField _setScale(mixed $arg0)
* @method UIxPasswordField _setPosition(array $arg0)
* @method UIxPasswordField _setHeight(mixed $arg0)
* @method UIxPasswordField setWindow($mixed)
* @method UIxPasswordField _setEnabled(mixed $arg0)
* @method UIxPasswordField setForm($mixed)
* @method UIxPasswordField _setScreenPosition(array $arg0)
* @method UIxPasswordField _setScreenY(mixed $arg0)
* @method UIxPasswordField _setScreenX(mixed $arg0)
* @method UIxPasswordField _setClassesString(mixed $arg0)
* @method UIxPasswordField _setAnchors(array $arg0)
* @method UIxPasswordField setEffects($mixed)
* @method UIxPasswordField _setAnchorFlags(array $arg0)
* @method UIxPasswordField _setLeftAnchor(mixed $arg0)
* @method UIxPasswordField _setRightAnchor(mixed $arg0)
* @method UIxPasswordField _setTopAnchor(mixed $arg0)
* @method UIxPasswordField _setBottomAnchor(mixed $arg0) */

class UIxPasswordField extends UXPasswordField {
    use Cascadable;
}
