<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\layout\UXPane;

/**
* @method UIxPane setChildren($mixed)
* @method UIxPane _setMinHeight(mixed $arg0)
* @method UIxPane _setMaxWidth(mixed $arg0)
* @method UIxPane _setMinWidth(mixed $arg0)
* @method UIxPane _setMaxHeight(mixed $arg0)
* @method UIxPane _setPadding(mixed $arg0)
* @method UIxPane _setMinSize(array $arg0)
* @method UIxPane _setMaxSize(array $arg0)
* @method UIxPane _setBackgroundColor(mixed $arg0)
* @method UIxPane _setPaddingTop(mixed $arg0)
* @method UIxPane _setPaddingRight(mixed $arg0)
* @method UIxPane _setPaddingLeft(mixed $arg0)
* @method UIxPane _setPaddingBottom(mixed $arg0)
* @method UIxPane setPrefSize($mixed)
* @method UIxPane setStylesheets($mixed)
* @method UIxPane setChildrenUnmodifiable($mixed)
* @method UIxPane _setCache(mixed $arg0)
* @method UIxPane _setRotate(mixed $arg0)
* @method UIxPane _setId(mixed $arg0)
* @method UIxPane _setOpacity(mixed $arg0)
* @method UIxPane setHover($mixed)
* @method UIxPane setPressed($mixed)
* @method UIxPane setFocused($mixed)
* @method UIxPane _setManaged(mixed $arg0)
* @method UIxPane _setStyle(mixed $arg0)
* @method UIxPane _setVisible(mixed $arg0)
* @method UIxPane setDisabled($mixed)
* @method UIxPane _setFocusTraversable(mixed $arg0)
* @method UIxPane setClasses($mixed)
* @method UIxPane _setBlendMode( $arg0)
* @method UIxPane _setPickOnBounds(mixed $arg0)
* @method UIxPane setResizable($mixed)
* @method UIxPane _setScaleX(mixed $arg0)
* @method UIxPane _setScaleY(mixed $arg0)
* @method UIxPane _setTranslateX(mixed $arg0)
* @method UIxPane _setTranslateY(mixed $arg0)
* @method UIxPane _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxPane setBaselineOffset($mixed)
* @method UIxPane _setClip(php\gui\UXNode $arg0)
* @method UIxPane _setDepthTest( $arg0)
* @method UIxPane _setTranslateZ(mixed $arg0)
* @method UIxPane _setCacheHint( $arg0)
* @method UIxPane _setMouseTransparent(mixed $arg0)
* @method UIxPane setContentBias($mixed)
* @method UIxPane _setScaleZ(mixed $arg0)
* @method UIxPane setParent($mixed)
* @method UIxPane _setSize(array $arg0)
* @method UIxPane setLayoutBounds($mixed)
* @method UIxPane setScene($mixed)
* @method UIxPane _setWidth(mixed $arg0)
* @method UIxPane setBoundsInParent($mixed)
* @method UIxPane _setX(mixed $arg0)
* @method UIxPane _setY(mixed $arg0)
* @method UIxPane _setUserData(mixed $arg0)
* @method UIxPane _setCursor(mixed $arg0)
* @method UIxPane _setPosition(array $arg0)
* @method UIxPane _setScale(mixed $arg0)
* @method UIxPane _setHeight(mixed $arg0)
* @method UIxPane setWindow($mixed)
* @method UIxPane _setEnabled(mixed $arg0)
* @method UIxPane setForm($mixed)
* @method UIxPane _setScreenPosition(array $arg0)
* @method UIxPane _setScreenX(mixed $arg0)
* @method UIxPane _setScreenY(mixed $arg0)
* @method UIxPane _setAnchors(array $arg0)
* @method UIxPane _setAnchorFlags(array $arg0)
* @method UIxPane _setLeftAnchor(mixed $arg0)
* @method UIxPane _setBottomAnchor(mixed $arg0)
* @method UIxPane setEffects($mixed)
* @method UIxPane _setRightAnchor(mixed $arg0)
* @method UIxPane _setTopAnchor(mixed $arg0)
* @method UIxPane _setClassesString(mixed $arg0) */

class UIxPane extends UXPane {
    use Cascadable;
}
