<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXProgressBar;

/**
* @method UIxProgressBar setProgressK($mixed)
* @method UIxProgressBar setIndeterminate($mixed)
* @method UIxProgressBar _setProgress(mixed $arg0)
* @method UIxProgressBar setResizable($mixed)
* @method UIxProgressBar _setTooltip(php\gui\UXTooltip $arg0)
* @method UIxProgressBar _setContextMenu(php\gui\UXContextMenu $arg0)
* @method UIxProgressBar _setTooltipText(mixed $arg0)
* @method UIxProgressBar _setMinHeight(mixed $arg0)
* @method UIxProgressBar _setMaxWidth(mixed $arg0)
* @method UIxProgressBar _setMinWidth(mixed $arg0)
* @method UIxProgressBar _setPadding(mixed $arg0)
* @method UIxProgressBar _setMaxHeight(mixed $arg0)
* @method UIxProgressBar _setMaxSize(array $arg0)
* @method UIxProgressBar _setMinSize(array $arg0)
* @method UIxProgressBar _setBackgroundColor(mixed $arg0)
* @method UIxProgressBar _setPaddingLeft(mixed $arg0)
* @method UIxProgressBar _setPaddingTop(mixed $arg0)
* @method UIxProgressBar _setPaddingRight(mixed $arg0)
* @method UIxProgressBar _setPaddingBottom(mixed $arg0)
* @method UIxProgressBar setPrefSize($mixed)
* @method UIxProgressBar setStylesheets($mixed)
* @method UIxProgressBar setChildrenUnmodifiable($mixed)
* @method UIxProgressBar _setCache(mixed $arg0)
* @method UIxProgressBar _setRotate(mixed $arg0)
* @method UIxProgressBar _setId(mixed $arg0)
* @method UIxProgressBar _setScaleX(mixed $arg0)
* @method UIxProgressBar _setScaleY(mixed $arg0)
* @method UIxProgressBar _setTranslateX(mixed $arg0)
* @method UIxProgressBar _setTranslateY(mixed $arg0)
* @method UIxProgressBar _setOpacity(mixed $arg0)
* @method UIxProgressBar setDisabled($mixed)
* @method UIxProgressBar _setStyle(mixed $arg0)
* @method UIxProgressBar _setManaged(mixed $arg0)
* @method UIxProgressBar setPressed($mixed)
* @method UIxProgressBar _setVisible(mixed $arg0)
* @method UIxProgressBar setHover($mixed)
* @method UIxProgressBar setFocused($mixed)
* @method UIxProgressBar setClasses($mixed)
* @method UIxProgressBar _setBlendMode( $arg0)
* @method UIxProgressBar _setPickOnBounds(mixed $arg0)
* @method UIxProgressBar _setFocusTraversable(mixed $arg0)
* @method UIxProgressBar _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxProgressBar setBaselineOffset($mixed)
* @method UIxProgressBar _setClip(php\gui\UXNode $arg0)
* @method UIxProgressBar _setDepthTest( $arg0)
* @method UIxProgressBar setContentBias($mixed)
* @method UIxProgressBar _setTranslateZ(mixed $arg0)
* @method UIxProgressBar _setCacheHint( $arg0)
* @method UIxProgressBar _setMouseTransparent(mixed $arg0)
* @method UIxProgressBar _setScaleZ(mixed $arg0)
* @method UIxProgressBar setParent($mixed)
* @method UIxProgressBar _setSize(array $arg0)
* @method UIxProgressBar setLayoutBounds($mixed)
* @method UIxProgressBar setScene($mixed)
* @method UIxProgressBar _setWidth(mixed $arg0)
* @method UIxProgressBar _setX(mixed $arg0)
* @method UIxProgressBar _setY(mixed $arg0)
* @method UIxProgressBar setBoundsInParent($mixed)
* @method UIxProgressBar _setCursor(mixed $arg0)
* @method UIxProgressBar _setUserData(mixed $arg0)
* @method UIxProgressBar _setPosition(array $arg0)
* @method UIxProgressBar _setScale(mixed $arg0)
* @method UIxProgressBar _setHeight(mixed $arg0)
* @method UIxProgressBar setWindow($mixed)
* @method UIxProgressBar setForm($mixed)
* @method UIxProgressBar _setEnabled(mixed $arg0)
* @method UIxProgressBar _setScreenPosition(array $arg0)
* @method UIxProgressBar _setScreenY(mixed $arg0)
* @method UIxProgressBar _setScreenX(mixed $arg0)
* @method UIxProgressBar _setRightAnchor(mixed $arg0)
* @method UIxProgressBar _setLeftAnchor(mixed $arg0)
* @method UIxProgressBar _setBottomAnchor(mixed $arg0)
* @method UIxProgressBar _setClassesString(mixed $arg0)
* @method UIxProgressBar _setAnchorFlags(array $arg0)
* @method UIxProgressBar _setAnchors(array $arg0)
* @method UIxProgressBar _setTopAnchor(mixed $arg0)
* @method UIxProgressBar setEffects($mixed) */

class UIxProgressBar extends UXProgressBar {
    use Cascadable;
}
