<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXProgressIndicator;

/**
* @method UIxProgressIndicator setProgressK($mixed)
* @method UIxProgressIndicator setIndeterminate($mixed)
* @method UIxProgressIndicator _setProgress(mixed $arg0)
* @method UIxProgressIndicator setResizable($mixed)
* @method UIxProgressIndicator _setTooltip(php\gui\UXTooltip $arg0)
* @method UIxProgressIndicator _setContextMenu(php\gui\UXContextMenu $arg0)
* @method UIxProgressIndicator _setTooltipText(mixed $arg0)
* @method UIxProgressIndicator _setMinHeight(mixed $arg0)
* @method UIxProgressIndicator _setMinWidth(mixed $arg0)
* @method UIxProgressIndicator _setMaxWidth(mixed $arg0)
* @method UIxProgressIndicator _setMaxHeight(mixed $arg0)
* @method UIxProgressIndicator _setPadding(mixed $arg0)
* @method UIxProgressIndicator _setMaxSize(array $arg0)
* @method UIxProgressIndicator _setMinSize(array $arg0)
* @method UIxProgressIndicator _setBackgroundColor(mixed $arg0)
* @method UIxProgressIndicator _setPaddingRight(mixed $arg0)
* @method UIxProgressIndicator setPrefSize($mixed)
* @method UIxProgressIndicator _setPaddingBottom(mixed $arg0)
* @method UIxProgressIndicator _setPaddingLeft(mixed $arg0)
* @method UIxProgressIndicator _setPaddingTop(mixed $arg0)
* @method UIxProgressIndicator setStylesheets($mixed)
* @method UIxProgressIndicator setChildrenUnmodifiable($mixed)
* @method UIxProgressIndicator _setCache(mixed $arg0)
* @method UIxProgressIndicator _setRotate(mixed $arg0)
* @method UIxProgressIndicator _setId(mixed $arg0)
* @method UIxProgressIndicator _setScaleX(mixed $arg0)
* @method UIxProgressIndicator _setScaleY(mixed $arg0)
* @method UIxProgressIndicator _setTranslateX(mixed $arg0)
* @method UIxProgressIndicator _setTranslateY(mixed $arg0)
* @method UIxProgressIndicator _setOpacity(mixed $arg0)
* @method UIxProgressIndicator _setStyle(mixed $arg0)
* @method UIxProgressIndicator _setVisible(mixed $arg0)
* @method UIxProgressIndicator setDisabled($mixed)
* @method UIxProgressIndicator _setManaged(mixed $arg0)
* @method UIxProgressIndicator setFocused($mixed)
* @method UIxProgressIndicator setHover($mixed)
* @method UIxProgressIndicator setPressed($mixed)
* @method UIxProgressIndicator _setPickOnBounds(mixed $arg0)
* @method UIxProgressIndicator setClasses($mixed)
* @method UIxProgressIndicator _setBlendMode( $arg0)
* @method UIxProgressIndicator _setFocusTraversable(mixed $arg0)
* @method UIxProgressIndicator _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxProgressIndicator setBaselineOffset($mixed)
* @method UIxProgressIndicator _setClip(php\gui\UXNode $arg0)
* @method UIxProgressIndicator _setDepthTest( $arg0)
* @method UIxProgressIndicator _setScaleZ(mixed $arg0)
* @method UIxProgressIndicator _setTranslateZ(mixed $arg0)
* @method UIxProgressIndicator _setCacheHint( $arg0)
* @method UIxProgressIndicator _setMouseTransparent(mixed $arg0)
* @method UIxProgressIndicator setContentBias($mixed)
* @method UIxProgressIndicator setParent($mixed)
* @method UIxProgressIndicator _setSize(array $arg0)
* @method UIxProgressIndicator setLayoutBounds($mixed)
* @method UIxProgressIndicator _setWidth(mixed $arg0)
* @method UIxProgressIndicator setScene($mixed)
* @method UIxProgressIndicator setBoundsInParent($mixed)
* @method UIxProgressIndicator _setX(mixed $arg0)
* @method UIxProgressIndicator _setY(mixed $arg0)
* @method UIxProgressIndicator _setCursor(mixed $arg0)
* @method UIxProgressIndicator _setUserData(mixed $arg0)
* @method UIxProgressIndicator _setScale(mixed $arg0)
* @method UIxProgressIndicator _setPosition(array $arg0)
* @method UIxProgressIndicator _setHeight(mixed $arg0)
* @method UIxProgressIndicator setWindow($mixed)
* @method UIxProgressIndicator setForm($mixed)
* @method UIxProgressIndicator _setEnabled(mixed $arg0)
* @method UIxProgressIndicator _setScreenPosition(array $arg0)
* @method UIxProgressIndicator _setScreenY(mixed $arg0)
* @method UIxProgressIndicator _setScreenX(mixed $arg0)
* @method UIxProgressIndicator setEffects($mixed)
* @method UIxProgressIndicator _setRightAnchor(mixed $arg0)
* @method UIxProgressIndicator _setClassesString(mixed $arg0)
* @method UIxProgressIndicator _setLeftAnchor(mixed $arg0)
* @method UIxProgressIndicator _setAnchors(array $arg0)
* @method UIxProgressIndicator _setTopAnchor(mixed $arg0)
* @method UIxProgressIndicator _setBottomAnchor(mixed $arg0)
* @method UIxProgressIndicator _setAnchorFlags(array $arg0) */

class UIxProgressIndicator extends UXProgressIndicator {
    use Cascadable;
}
