<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\layout\UXPanel;

/**
* @method UIxPanel _setTitle(mixed $arg0)
* @method UIxPanel _setTitleOffset(mixed $arg0)
* @method UIxPanel _setTitlePosition( $arg0)
* @method UIxPanel _setBorderColor(mixed $arg0)
* @method UIxPanel _setBorderStyle(mixed $arg0)
* @method UIxPanel _setBorderRadius(mixed $arg0)
* @method UIxPanel _setTitleColor(mixed $arg0)
* @method UIxPanel _setTitleFont(php\gui\text\UXFont $arg0)
* @method UIxPanel _setBorderWidth(mixed $arg0)
* @method UIxPanel _setBackgroundColor(mixed $arg0)
* @method UIxPanel setChildren($mixed)
* @method UIxPanel _setMaxWidth(mixed $arg0)
* @method UIxPanel _setMinWidth(mixed $arg0)
* @method UIxPanel _setMinHeight(mixed $arg0)
* @method UIxPanel _setMaxHeight(mixed $arg0)
* @method UIxPanel _setPadding(mixed $arg0)
* @method UIxPanel _setMinSize(array $arg0)
* @method UIxPanel _setMaxSize(array $arg0)
* @method UIxPanel _setPaddingRight(mixed $arg0)
* @method UIxPanel _setPaddingBottom(mixed $arg0)
* @method UIxPanel _setPaddingLeft(mixed $arg0)
* @method UIxPanel _setPaddingTop(mixed $arg0)
* @method UIxPanel setPrefSize($mixed)
* @method UIxPanel setStylesheets($mixed)
* @method UIxPanel setChildrenUnmodifiable($mixed)
* @method UIxPanel _setCache(mixed $arg0)
* @method UIxPanel _setRotate(mixed $arg0)
* @method UIxPanel _setId(mixed $arg0)
* @method UIxPanel _setOpacity(mixed $arg0)
* @method UIxPanel setFocused($mixed)
* @method UIxPanel _setVisible(mixed $arg0)
* @method UIxPanel _setManaged(mixed $arg0)
* @method UIxPanel setPressed($mixed)
* @method UIxPanel setHover($mixed)
* @method UIxPanel _setStyle(mixed $arg0)
* @method UIxPanel setDisabled($mixed)
* @method UIxPanel _setBlendMode( $arg0)
* @method UIxPanel setClasses($mixed)
* @method UIxPanel _setPickOnBounds(mixed $arg0)
* @method UIxPanel _setFocusTraversable(mixed $arg0)
* @method UIxPanel setResizable($mixed)
* @method UIxPanel _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxPanel setBaselineOffset($mixed)
* @method UIxPanel _setScaleX(mixed $arg0)
* @method UIxPanel _setScaleY(mixed $arg0)
* @method UIxPanel _setTranslateX(mixed $arg0)
* @method UIxPanel _setTranslateY(mixed $arg0)
* @method UIxPanel _setClip(php\gui\UXNode $arg0)
* @method UIxPanel _setDepthTest( $arg0)
* @method UIxPanel _setScaleZ(mixed $arg0)
* @method UIxPanel _setTranslateZ(mixed $arg0)
* @method UIxPanel _setCacheHint( $arg0)
* @method UIxPanel _setMouseTransparent(mixed $arg0)
* @method UIxPanel setContentBias($mixed)
* @method UIxPanel setParent($mixed)
* @method UIxPanel _setSize(array $arg0)
* @method UIxPanel setScene($mixed)
* @method UIxPanel _setWidth(mixed $arg0)
* @method UIxPanel setLayoutBounds($mixed)
* @method UIxPanel setBoundsInParent($mixed)
* @method UIxPanel _setX(mixed $arg0)
* @method UIxPanel _setY(mixed $arg0)
* @method UIxPanel _setUserData(mixed $arg0)
* @method UIxPanel _setCursor(mixed $arg0)
* @method UIxPanel _setScale(mixed $arg0)
* @method UIxPanel _setHeight(mixed $arg0)
* @method UIxPanel setWindow($mixed)
* @method UIxPanel _setPosition(array $arg0)
* @method UIxPanel setForm($mixed)
* @method UIxPanel _setEnabled(mixed $arg0)
* @method UIxPanel _setScreenPosition(array $arg0)
* @method UIxPanel _setScreenX(mixed $arg0)
* @method UIxPanel _setScreenY(mixed $arg0)
* @method UIxPanel _setRightAnchor(php\gui\UXNode $arg0, mixed $arg1)
* @method UIxPanel _setTopAnchor(php\gui\UXNode $arg0, mixed $arg1)
* @method UIxPanel _setClassesString(mixed $arg0)
* @method UIxPanel _setBottomAnchor(php\gui\UXNode $arg0, mixed $arg1)
* @method UIxPanel _setAnchors(array $arg0)
* @method UIxPanel _setLeftAnchor(php\gui\UXNode $arg0, mixed $arg1)
* @method UIxPanel _setAnchorFlags(array $arg0)
* @method UIxPanel setEffects($mixed) */

class UIxPanel extends UXPanel {
    use Cascadable;
}
