<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\shape\UXPolygon;

/**
* @method UIxPolygon setPoints($mixed)
* @method UIxPolygon _setSmooth(mixed $arg0)
* @method UIxPolygon _setStrokeWidth(mixed $arg0)
* @method UIxPolygon _setStrokeType( $arg0)
* @method UIxPolygon _setStrokeColor(mixed $arg0)
* @method UIxPolygon _setFillColor(mixed $arg0)
* @method UIxPolygon _setCache(mixed $arg0)
* @method UIxPolygon _setRotate(mixed $arg0)
* @method UIxPolygon _setId(mixed $arg0)
* @method UIxPolygon _setScaleX(mixed $arg0)
* @method UIxPolygon _setScaleY(mixed $arg0)
* @method UIxPolygon _setTranslateX(mixed $arg0)
* @method UIxPolygon _setTranslateY(mixed $arg0)
* @method UIxPolygon _setOpacity(mixed $arg0)
* @method UIxPolygon _setStyle(mixed $arg0)
* @method UIxPolygon _setVisible(mixed $arg0)
* @method UIxPolygon _setManaged(mixed $arg0)
* @method UIxPolygon setDisabled($mixed)
* @method UIxPolygon setPressed($mixed)
* @method UIxPolygon setHover($mixed)
* @method UIxPolygon setFocused($mixed)
* @method UIxPolygon _setPickOnBounds(mixed $arg0)
* @method UIxPolygon _setBlendMode( $arg0)
* @method UIxPolygon setClasses($mixed)
* @method UIxPolygon _setFocusTraversable(mixed $arg0)
* @method UIxPolygon setResizable($mixed)
* @method UIxPolygon _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxPolygon setBaselineOffset($mixed)
* @method UIxPolygon _setClip(php\gui\UXNode $arg0)
* @method UIxPolygon _setDepthTest( $arg0)
* @method UIxPolygon _setScaleZ(mixed $arg0)
* @method UIxPolygon _setTranslateZ(mixed $arg0)
* @method UIxPolygon _setCacheHint( $arg0)
* @method UIxPolygon _setMouseTransparent(mixed $arg0)
* @method UIxPolygon setContentBias($mixed)
* @method UIxPolygon setParent($mixed)
* @method UIxPolygon _setSize(array $arg0)
* @method UIxPolygon setLayoutBounds($mixed)
* @method UIxPolygon _setWidth(mixed $arg0)
* @method UIxPolygon setScene($mixed)
* @method UIxPolygon _setX(mixed $arg0)
* @method UIxPolygon _setY(mixed $arg0)
* @method UIxPolygon setBoundsInParent($mixed)
* @method UIxPolygon _setCursor(mixed $arg0)
* @method UIxPolygon _setUserData(mixed $arg0)
* @method UIxPolygon _setPosition(array $arg0)
* @method UIxPolygon _setScale(mixed $arg0)
* @method UIxPolygon _setHeight(mixed $arg0)
* @method UIxPolygon setWindow($mixed)
* @method UIxPolygon _setEnabled(mixed $arg0)
* @method UIxPolygon _setScreenPosition(array $arg0)
* @method UIxPolygon setForm($mixed)
* @method UIxPolygon _setScreenX(mixed $arg0)
* @method UIxPolygon _setScreenY(mixed $arg0)
* @method UIxPolygon _setClassesString(mixed $arg0)
* @method UIxPolygon _setAnchors(array $arg0)
* @method UIxPolygon _setTopAnchor(mixed $arg0)
* @method UIxPolygon _setAnchorFlags(array $arg0)
* @method UIxPolygon _setRightAnchor(mixed $arg0)
* @method UIxPolygon _setLeftAnchor(mixed $arg0)
* @method UIxPolygon _setBottomAnchor(mixed $arg0)
* @method UIxPolygon setEffects($mixed) */

class UIxPolygon extends UXPolygon {
    use Cascadable;
}
