<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXRadioGroupPane;

/**
* @method UIxRadioGroupPane _setItems(php\gui\UXList $arg0)
* @method UIxRadioGroupPane _setSelected(mixed $arg0)
* @method UIxRadioGroupPane _setOrientation( $arg0)
* @method UIxRadioGroupPane _setTextColor(mixed $arg0)
* @method UIxRadioGroupPane _setSelectedIndex(mixed $arg0)
* @method UIxRadioGroupPane _setFont(php\gui\text\UXFont $arg0)
* @method UIxRadioGroupPane _setSpacing(mixed $arg0)
* @method UIxRadioGroupPane _setAlignment( $arg0)
* @method UIxRadioGroupPane _setFillWidth(mixed $arg0)
* @method UIxRadioGroupPane setChildren($mixed)
* @method UIxRadioGroupPane _setMaxWidth(mixed $arg0)
* @method UIxRadioGroupPane _setMinWidth(mixed $arg0)
* @method UIxRadioGroupPane _setMinHeight(mixed $arg0)
* @method UIxRadioGroupPane _setMaxHeight(mixed $arg0)
* @method UIxRadioGroupPane _setPadding(mixed $arg0)
* @method UIxRadioGroupPane _setMinSize(array $arg0)
* @method UIxRadioGroupPane _setMaxSize(array $arg0)
* @method UIxRadioGroupPane _setBackgroundColor(mixed $arg0)
* @method UIxRadioGroupPane _setPaddingBottom(mixed $arg0)
* @method UIxRadioGroupPane _setPaddingTop(mixed $arg0)
* @method UIxRadioGroupPane _setPaddingRight(mixed $arg0)
* @method UIxRadioGroupPane _setPaddingLeft(mixed $arg0)
* @method UIxRadioGroupPane setPrefSize($mixed)
* @method UIxRadioGroupPane setStylesheets($mixed)
* @method UIxRadioGroupPane setChildrenUnmodifiable($mixed)
* @method UIxRadioGroupPane _setCache(mixed $arg0)
* @method UIxRadioGroupPane _setRotate(mixed $arg0)
* @method UIxRadioGroupPane _setId(mixed $arg0)
* @method UIxRadioGroupPane _setOpacity(mixed $arg0)
* @method UIxRadioGroupPane _setVisible(mixed $arg0)
* @method UIxRadioGroupPane setDisabled($mixed)
* @method UIxRadioGroupPane _setStyle(mixed $arg0)
* @method UIxRadioGroupPane _setManaged(mixed $arg0)
* @method UIxRadioGroupPane setPressed($mixed)
* @method UIxRadioGroupPane setHover($mixed)
* @method UIxRadioGroupPane setFocused($mixed)
* @method UIxRadioGroupPane _setPickOnBounds(mixed $arg0)
* @method UIxRadioGroupPane _setBlendMode( $arg0)
* @method UIxRadioGroupPane setClasses($mixed)
* @method UIxRadioGroupPane _setFocusTraversable(mixed $arg0)
* @method UIxRadioGroupPane setResizable($mixed)
* @method UIxRadioGroupPane _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxRadioGroupPane setBaselineOffset($mixed)
* @method UIxRadioGroupPane _setScaleX(mixed $arg0)
* @method UIxRadioGroupPane _setScaleY(mixed $arg0)
* @method UIxRadioGroupPane _setTranslateX(mixed $arg0)
* @method UIxRadioGroupPane _setTranslateY(mixed $arg0)
* @method UIxRadioGroupPane _setClip(php\gui\UXNode $arg0)
* @method UIxRadioGroupPane _setDepthTest( $arg0)
* @method UIxRadioGroupPane _setScaleZ(mixed $arg0)
* @method UIxRadioGroupPane _setTranslateZ(mixed $arg0)
* @method UIxRadioGroupPane _setCacheHint( $arg0)
* @method UIxRadioGroupPane _setMouseTransparent(mixed $arg0)
* @method UIxRadioGroupPane setContentBias($mixed)
* @method UIxRadioGroupPane setParent($mixed)
* @method UIxRadioGroupPane _setSize(array $arg0)
* @method UIxRadioGroupPane _setWidth(mixed $arg0)
* @method UIxRadioGroupPane setScene($mixed)
* @method UIxRadioGroupPane setLayoutBounds($mixed)
* @method UIxRadioGroupPane _setY(mixed $arg0)
* @method UIxRadioGroupPane _setX(mixed $arg0)
* @method UIxRadioGroupPane _setUserData(mixed $arg0)
* @method UIxRadioGroupPane _setCursor(mixed $arg0)
* @method UIxRadioGroupPane setBoundsInParent($mixed)
* @method UIxRadioGroupPane _setPosition(array $arg0)
* @method UIxRadioGroupPane _setScale(mixed $arg0)
* @method UIxRadioGroupPane _setHeight(mixed $arg0)
* @method UIxRadioGroupPane setWindow($mixed)
* @method UIxRadioGroupPane _setEnabled(mixed $arg0)
* @method UIxRadioGroupPane setForm($mixed)
* @method UIxRadioGroupPane _setScreenPosition(array $arg0)
* @method UIxRadioGroupPane _setScreenX(mixed $arg0)
* @method UIxRadioGroupPane _setScreenY(mixed $arg0)
* @method UIxRadioGroupPane _setClassesString(mixed $arg0)
* @method UIxRadioGroupPane _setRightAnchor(mixed $arg0)
* @method UIxRadioGroupPane _setTopAnchor(mixed $arg0)
* @method UIxRadioGroupPane _setAnchorFlags(array $arg0)
* @method UIxRadioGroupPane _setBottomAnchor(mixed $arg0)
* @method UIxRadioGroupPane setEffects($mixed)
* @method UIxRadioGroupPane _setLeftAnchor(mixed $arg0)
* @method UIxRadioGroupPane _setAnchors(array $arg0) */

class UIxRadioGroupPane extends UXRadioGroupPane {
    use Cascadable;
}
