<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\shape\UXRectangle;

/**
* @method UIxRectangle _setArcHeight(mixed $arg0)
* @method UIxRectangle _setArcWidth(mixed $arg0)
* @method UIxRectangle _setSmooth(mixed $arg0)
* @method UIxRectangle _setStrokeType( $arg0)
* @method UIxRectangle _setStrokeWidth(mixed $arg0)
* @method UIxRectangle _setStrokeColor(mixed $arg0)
* @method UIxRectangle _setFillColor(mixed $arg0)
* @method UIxRectangle _setCache(mixed $arg0)
* @method UIxRectangle _setRotate(mixed $arg0)
* @method UIxRectangle _setId(mixed $arg0)
* @method UIxRectangle _setOpacity(mixed $arg0)
* @method UIxRectangle _setStyle(mixed $arg0)
* @method UIxRectangle setDisabled($mixed)
* @method UIxRectangle _setVisible(mixed $arg0)
* @method UIxRectangle _setManaged(mixed $arg0)
* @method UIxRectangle setPressed($mixed)
* @method UIxRectangle setHover($mixed)
* @method UIxRectangle setFocused($mixed)
* @method UIxRectangle setClasses($mixed)
* @method UIxRectangle _setBlendMode( $arg0)
* @method UIxRectangle _setPickOnBounds(mixed $arg0)
* @method UIxRectangle _setFocusTraversable(mixed $arg0)
* @method UIxRectangle _setScaleX(mixed $arg0)
* @method UIxRectangle _setScaleY(mixed $arg0)
* @method UIxRectangle _setTranslateX(mixed $arg0)
* @method UIxRectangle _setTranslateY(mixed $arg0)
* @method UIxRectangle setResizable($mixed)
* @method UIxRectangle _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxRectangle setBaselineOffset($mixed)
* @method UIxRectangle _setClip(php\gui\UXNode $arg0)
* @method UIxRectangle _setDepthTest( $arg0)
* @method UIxRectangle _setScaleZ(mixed $arg0)
* @method UIxRectangle setContentBias($mixed)
* @method UIxRectangle _setCacheHint( $arg0)
* @method UIxRectangle _setMouseTransparent(mixed $arg0)
* @method UIxRectangle _setTranslateZ(mixed $arg0)
* @method UIxRectangle setParent($mixed)
* @method UIxRectangle _setSize(array $arg0)
* @method UIxRectangle setLayoutBounds($mixed)
* @method UIxRectangle _setWidth(mixed $arg0)
* @method UIxRectangle setScene($mixed)
* @method UIxRectangle setBoundsInParent($mixed)
* @method UIxRectangle _setX(mixed $arg0)
* @method UIxRectangle _setY(mixed $arg0)
* @method UIxRectangle _setCursor(mixed $arg0)
* @method UIxRectangle _setUserData(mixed $arg0)
* @method UIxRectangle _setPosition(array $arg0)
* @method UIxRectangle _setScale(mixed $arg0)
* @method UIxRectangle _setHeight(mixed $arg0)
* @method UIxRectangle setWindow($mixed)
* @method UIxRectangle _setEnabled(mixed $arg0)
* @method UIxRectangle setForm($mixed)
* @method UIxRectangle _setScreenPosition(array $arg0)
* @method UIxRectangle _setScreenY(mixed $arg0)
* @method UIxRectangle _setScreenX(mixed $arg0)
* @method UIxRectangle _setTopAnchor(mixed $arg0)
* @method UIxRectangle _setBottomAnchor(mixed $arg0)
* @method UIxRectangle setEffects($mixed)
* @method UIxRectangle _setRightAnchor(mixed $arg0)
* @method UIxRectangle _setClassesString(mixed $arg0)
* @method UIxRectangle _setLeftAnchor(mixed $arg0)
* @method UIxRectangle _setAnchorFlags(array $arg0)
* @method UIxRectangle _setAnchors(array $arg0) */

class UIxRectangle extends UXRectangle {
    use Cascadable;
}
