<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXSlider;

/**
* @method UIxSlider _setValue(mixed $arg0)
* @method UIxSlider _setMin(mixed $arg0)
* @method UIxSlider _setMax(mixed $arg0)
* @method UIxSlider _setOrientation( $arg0)
* @method UIxSlider _setShowTickLabels(mixed $arg0)
* @method UIxSlider _setSnapToTicks(mixed $arg0)
* @method UIxSlider _setBlockIncrement(mixed $arg0)
* @method UIxSlider _setMinorTickCount(mixed $arg0)
* @method UIxSlider _setMajorTickUnit(mixed $arg0)
* @method UIxSlider _setShowTickMarks(mixed $arg0)
* @method UIxSlider setResizable($mixed)
* @method UIxSlider _setTooltip(php\gui\UXTooltip $arg0)
* @method UIxSlider _setContextMenu(php\gui\UXContextMenu $arg0)
* @method UIxSlider _setTooltipText(mixed $arg0)
* @method UIxSlider _setMinHeight(mixed $arg0)
* @method UIxSlider _setMinWidth(mixed $arg0)
* @method UIxSlider _setMaxWidth(mixed $arg0)
* @method UIxSlider _setMaxHeight(mixed $arg0)
* @method UIxSlider _setPadding(mixed $arg0)
* @method UIxSlider _setMaxSize(array $arg0)
* @method UIxSlider _setMinSize(array $arg0)
* @method UIxSlider _setBackgroundColor(mixed $arg0)
* @method UIxSlider _setPaddingBottom(mixed $arg0)
* @method UIxSlider _setPaddingLeft(mixed $arg0)
* @method UIxSlider _setPaddingTop(mixed $arg0)
* @method UIxSlider _setPaddingRight(mixed $arg0)
* @method UIxSlider setPrefSize($mixed)
* @method UIxSlider setStylesheets($mixed)
* @method UIxSlider setChildrenUnmodifiable($mixed)
* @method UIxSlider _setCache(mixed $arg0)
* @method UIxSlider _setRotate(mixed $arg0)
* @method UIxSlider _setId(mixed $arg0)
* @method UIxSlider _setScaleX(mixed $arg0)
* @method UIxSlider _setScaleY(mixed $arg0)
* @method UIxSlider _setTranslateX(mixed $arg0)
* @method UIxSlider _setTranslateY(mixed $arg0)
* @method UIxSlider _setOpacity(mixed $arg0)
* @method UIxSlider setDisabled($mixed)
* @method UIxSlider _setStyle(mixed $arg0)
* @method UIxSlider _setManaged(mixed $arg0)
* @method UIxSlider _setVisible(mixed $arg0)
* @method UIxSlider setPressed($mixed)
* @method UIxSlider setFocused($mixed)
* @method UIxSlider setHover($mixed)
* @method UIxSlider _setPickOnBounds(mixed $arg0)
* @method UIxSlider _setBlendMode( $arg0)
* @method UIxSlider setClasses($mixed)
* @method UIxSlider _setFocusTraversable(mixed $arg0)
* @method UIxSlider _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxSlider setBaselineOffset($mixed)
* @method UIxSlider _setClip(php\gui\UXNode $arg0)
* @method UIxSlider _setScaleZ(mixed $arg0)
* @method UIxSlider _setDepthTest( $arg0)
* @method UIxSlider _setTranslateZ(mixed $arg0)
* @method UIxSlider _setMouseTransparent(mixed $arg0)
* @method UIxSlider _setCacheHint( $arg0)
* @method UIxSlider setContentBias($mixed)
* @method UIxSlider setParent($mixed)
* @method UIxSlider _setSize(array $arg0)
* @method UIxSlider setLayoutBounds($mixed)
* @method UIxSlider _setWidth(mixed $arg0)
* @method UIxSlider setScene($mixed)
* @method UIxSlider setBoundsInParent($mixed)
* @method UIxSlider _setUserData(mixed $arg0)
* @method UIxSlider _setCursor(mixed $arg0)
* @method UIxSlider _setX(mixed $arg0)
* @method UIxSlider _setY(mixed $arg0)
* @method UIxSlider _setScale(mixed $arg0)
* @method UIxSlider _setHeight(mixed $arg0)
* @method UIxSlider setWindow($mixed)
* @method UIxSlider _setPosition(array $arg0)
* @method UIxSlider setForm($mixed)
* @method UIxSlider _setEnabled(mixed $arg0)
* @method UIxSlider _setScreenPosition(array $arg0)
* @method UIxSlider _setScreenX(mixed $arg0)
* @method UIxSlider _setScreenY(mixed $arg0)
* @method UIxSlider _setClassesString(mixed $arg0)
* @method UIxSlider _setTopAnchor(mixed $arg0)
* @method UIxSlider _setBottomAnchor(mixed $arg0)
* @method UIxSlider _setAnchorFlags(array $arg0)
* @method UIxSlider _setAnchors(array $arg0)
* @method UIxSlider _setLeftAnchor(mixed $arg0)
* @method UIxSlider _setRightAnchor(mixed $arg0)
* @method UIxSlider setEffects($mixed) */

class UIxSlider extends UXSlider {
    use Cascadable;
}
