<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXSeparator;

/**
* @method UIxSeparator _setOrientation( $arg0)
* @method UIxSeparator _setHAlignment( $arg0)
* @method UIxSeparator _setVAlignment( $arg0)
* @method UIxSeparator setResizable($mixed)
* @method UIxSeparator _setTooltip(php\gui\UXTooltip $arg0)
* @method UIxSeparator _setContextMenu(php\gui\UXContextMenu $arg0)
* @method UIxSeparator _setTooltipText(mixed $arg0)
* @method UIxSeparator _setMinHeight(mixed $arg0)
* @method UIxSeparator _setMinWidth(mixed $arg0)
* @method UIxSeparator _setMaxWidth(mixed $arg0)
* @method UIxSeparator _setMaxHeight(mixed $arg0)
* @method UIxSeparator _setPadding(mixed $arg0)
* @method UIxSeparator _setMinSize(array $arg0)
* @method UIxSeparator _setMaxSize(array $arg0)
* @method UIxSeparator _setBackgroundColor(mixed $arg0)
* @method UIxSeparator setPrefSize($mixed)
* @method UIxSeparator _setPaddingLeft(mixed $arg0)
* @method UIxSeparator _setPaddingTop(mixed $arg0)
* @method UIxSeparator _setPaddingBottom(mixed $arg0)
* @method UIxSeparator _setPaddingRight(mixed $arg0)
* @method UIxSeparator setStylesheets($mixed)
* @method UIxSeparator setChildrenUnmodifiable($mixed)
* @method UIxSeparator _setCache(mixed $arg0)
* @method UIxSeparator _setRotate(mixed $arg0)
* @method UIxSeparator _setId(mixed $arg0)
* @method UIxSeparator _setOpacity(mixed $arg0)
* @method UIxSeparator _setVisible(mixed $arg0)
* @method UIxSeparator setDisabled($mixed)
* @method UIxSeparator _setManaged(mixed $arg0)
* @method UIxSeparator _setStyle(mixed $arg0)
* @method UIxSeparator setHover($mixed)
* @method UIxSeparator setPressed($mixed)
* @method UIxSeparator setFocused($mixed)
* @method UIxSeparator _setBlendMode( $arg0)
* @method UIxSeparator setClasses($mixed)
* @method UIxSeparator _setPickOnBounds(mixed $arg0)
* @method UIxSeparator _setFocusTraversable(mixed $arg0)
* @method UIxSeparator _setScaleX(mixed $arg0)
* @method UIxSeparator _setScaleY(mixed $arg0)
* @method UIxSeparator _setTranslateX(mixed $arg0)
* @method UIxSeparator _setTranslateY(mixed $arg0)
* @method UIxSeparator _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxSeparator setBaselineOffset($mixed)
* @method UIxSeparator _setClip(php\gui\UXNode $arg0)
* @method UIxSeparator _setDepthTest( $arg0)
* @method UIxSeparator _setScaleZ(mixed $arg0)
* @method UIxSeparator _setTranslateZ(mixed $arg0)
* @method UIxSeparator _setMouseTransparent(mixed $arg0)
* @method UIxSeparator _setCacheHint( $arg0)
* @method UIxSeparator setContentBias($mixed)
* @method UIxSeparator setParent($mixed)
* @method UIxSeparator _setSize(array $arg0)
* @method UIxSeparator setLayoutBounds($mixed)
* @method UIxSeparator _setWidth(mixed $arg0)
* @method UIxSeparator setScene($mixed)
* @method UIxSeparator _setX(mixed $arg0)
* @method UIxSeparator _setY(mixed $arg0)
* @method UIxSeparator setBoundsInParent($mixed)
* @method UIxSeparator _setCursor(mixed $arg0)
* @method UIxSeparator _setUserData(mixed $arg0)
* @method UIxSeparator _setPosition(array $arg0)
* @method UIxSeparator _setScale(mixed $arg0)
* @method UIxSeparator _setHeight(mixed $arg0)
* @method UIxSeparator setWindow($mixed)
* @method UIxSeparator setForm($mixed)
* @method UIxSeparator _setEnabled(mixed $arg0)
* @method UIxSeparator _setScreenPosition(array $arg0)
* @method UIxSeparator _setScreenY(mixed $arg0)
* @method UIxSeparator _setScreenX(mixed $arg0)
* @method UIxSeparator _setRightAnchor(mixed $arg0)
* @method UIxSeparator _setAnchors(array $arg0)
* @method UIxSeparator _setBottomAnchor(mixed $arg0)
* @method UIxSeparator _setTopAnchor(mixed $arg0)
* @method UIxSeparator _setAnchorFlags(array $arg0)
* @method UIxSeparator _setLeftAnchor(mixed $arg0)
* @method UIxSeparator _setClassesString(mixed $arg0)
* @method UIxSeparator setEffects($mixed) */

class UIxSeparator extends UXSeparator {
    use Cascadable;
}
