<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\layout\UXScrollPane;

/**
* @method UIxScrollPane _setContent(php\gui\UXNode $arg0)
* @method UIxScrollPane setScrollMinX($mixed)
* @method UIxScrollPane setScrollMinY($mixed)
* @method UIxScrollPane setScrollMaxX($mixed)
* @method UIxScrollPane setScrollMaxY($mixed)
* @method UIxScrollPane _setVbarPolicy( $arg0)
* @method UIxScrollPane _setFitToWidth(mixed $arg0)
* @method UIxScrollPane _setFitToHeight(mixed $arg0)
* @method UIxScrollPane _setHbarPolicy( $arg0)
* @method UIxScrollPane _setViewportBounds(mixed $arg0)
* @method UIxScrollPane _setScrollX(mixed $arg0)
* @method UIxScrollPane _setScrollY(mixed $arg0)
* @method UIxScrollPane setResizable($mixed)
* @method UIxScrollPane _setTooltip(php\gui\UXTooltip $arg0)
* @method UIxScrollPane _setContextMenu(php\gui\UXContextMenu $arg0)
* @method UIxScrollPane _setTooltipText(mixed $arg0)
* @method UIxScrollPane _setMinHeight(mixed $arg0)
* @method UIxScrollPane _setMaxWidth(mixed $arg0)
* @method UIxScrollPane _setMinWidth(mixed $arg0)
* @method UIxScrollPane _setMaxHeight(mixed $arg0)
* @method UIxScrollPane _setPadding(mixed $arg0)
* @method UIxScrollPane _setMinSize(array $arg0)
* @method UIxScrollPane _setMaxSize(array $arg0)
* @method UIxScrollPane _setBackgroundColor(mixed $arg0)
* @method UIxScrollPane setPrefSize($mixed)
* @method UIxScrollPane _setPaddingLeft(mixed $arg0)
* @method UIxScrollPane _setPaddingBottom(mixed $arg0)
* @method UIxScrollPane _setPaddingTop(mixed $arg0)
* @method UIxScrollPane _setPaddingRight(mixed $arg0)
* @method UIxScrollPane setStylesheets($mixed)
* @method UIxScrollPane setChildrenUnmodifiable($mixed)
* @method UIxScrollPane _setCache(mixed $arg0)
* @method UIxScrollPane _setRotate(mixed $arg0)
* @method UIxScrollPane _setId(mixed $arg0)
* @method UIxScrollPane _setOpacity(mixed $arg0)
* @method UIxScrollPane _setManaged(mixed $arg0)
* @method UIxScrollPane _setVisible(mixed $arg0)
* @method UIxScrollPane setFocused($mixed)
* @method UIxScrollPane _setStyle(mixed $arg0)
* @method UIxScrollPane setDisabled($mixed)
* @method UIxScrollPane setPressed($mixed)
* @method UIxScrollPane setHover($mixed)
* @method UIxScrollPane _setBlendMode( $arg0)
* @method UIxScrollPane _setPickOnBounds(mixed $arg0)
* @method UIxScrollPane setClasses($mixed)
* @method UIxScrollPane _setFocusTraversable(mixed $arg0)
* @method UIxScrollPane _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxScrollPane setBaselineOffset($mixed)
* @method UIxScrollPane _setClip(php\gui\UXNode $arg0)
* @method UIxScrollPane _setScaleX(mixed $arg0)
* @method UIxScrollPane _setScaleY(mixed $arg0)
* @method UIxScrollPane _setTranslateX(mixed $arg0)
* @method UIxScrollPane _setTranslateY(mixed $arg0)
* @method UIxScrollPane _setDepthTest( $arg0)
* @method UIxScrollPane _setTranslateZ(mixed $arg0)
* @method UIxScrollPane _setCacheHint( $arg0)
* @method UIxScrollPane _setMouseTransparent(mixed $arg0)
* @method UIxScrollPane setContentBias($mixed)
* @method UIxScrollPane _setScaleZ(mixed $arg0)
* @method UIxScrollPane setParent($mixed)
* @method UIxScrollPane _setSize(array $arg0)
* @method UIxScrollPane setLayoutBounds($mixed)
* @method UIxScrollPane _setWidth(mixed $arg0)
* @method UIxScrollPane setScene($mixed)
* @method UIxScrollPane setBoundsInParent($mixed)
* @method UIxScrollPane _setY(mixed $arg0)
* @method UIxScrollPane _setX(mixed $arg0)
* @method UIxScrollPane _setUserData(mixed $arg0)
* @method UIxScrollPane _setCursor(mixed $arg0)
* @method UIxScrollPane _setPosition(array $arg0)
* @method UIxScrollPane _setScale(mixed $arg0)
* @method UIxScrollPane _setHeight(mixed $arg0)
* @method UIxScrollPane setWindow($mixed)
* @method UIxScrollPane setForm($mixed)
* @method UIxScrollPane _setEnabled(mixed $arg0)
* @method UIxScrollPane _setScreenPosition(array $arg0)
* @method UIxScrollPane _setScreenY(mixed $arg0)
* @method UIxScrollPane _setScreenX(mixed $arg0)
* @method UIxScrollPane _setRightAnchor(mixed $arg0)
* @method UIxScrollPane _setBottomAnchor(mixed $arg0)
* @method UIxScrollPane _setAnchorFlags(array $arg0)
* @method UIxScrollPane setEffects($mixed)
* @method UIxScrollPane _setClassesString(mixed $arg0)
* @method UIxScrollPane _setAnchors(array $arg0)
* @method UIxScrollPane _setLeftAnchor(mixed $arg0)
* @method UIxScrollPane _setTopAnchor(mixed $arg0) */

class UIxScrollPane extends UXScrollPane {
    use Cascadable;
}
