<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\layout\UXStackPane;

/**
* @method UIxStackPane setChildren($mixed)
* @method UIxStackPane _setMinHeight(mixed $arg0)
* @method UIxStackPane _setMaxWidth(mixed $arg0)
* @method UIxStackPane _setMinWidth(mixed $arg0)
* @method UIxStackPane _setMaxHeight(mixed $arg0)
* @method UIxStackPane _setPadding(mixed $arg0)
* @method UIxStackPane _setMaxSize(array $arg0)
* @method UIxStackPane _setMinSize(array $arg0)
* @method UIxStackPane _setBackgroundColor(mixed $arg0)
* @method UIxStackPane _setPaddingBottom(mixed $arg0)
* @method UIxStackPane _setPaddingLeft(mixed $arg0)
* @method UIxStackPane _setPaddingRight(mixed $arg0)
* @method UIxStackPane _setPaddingTop(mixed $arg0)
* @method UIxStackPane setPrefSize($mixed)
* @method UIxStackPane setStylesheets($mixed)
* @method UIxStackPane setChildrenUnmodifiable($mixed)
* @method UIxStackPane _setCache(mixed $arg0)
* @method UIxStackPane _setRotate(mixed $arg0)
* @method UIxStackPane _setId(mixed $arg0)
* @method UIxStackPane _setOpacity(mixed $arg0)
* @method UIxStackPane _setVisible(mixed $arg0)
* @method UIxStackPane _setStyle(mixed $arg0)
* @method UIxStackPane setDisabled($mixed)
* @method UIxStackPane _setManaged(mixed $arg0)
* @method UIxStackPane setFocused($mixed)
* @method UIxStackPane setHover($mixed)
* @method UIxStackPane setPressed($mixed)
* @method UIxStackPane _setBlendMode( $arg0)
* @method UIxStackPane setClasses($mixed)
* @method UIxStackPane _setPickOnBounds(mixed $arg0)
* @method UIxStackPane _setFocusTraversable(mixed $arg0)
* @method UIxStackPane setResizable($mixed)
* @method UIxStackPane _setScaleX(mixed $arg0)
* @method UIxStackPane _setScaleY(mixed $arg0)
* @method UIxStackPane _setTranslateX(mixed $arg0)
* @method UIxStackPane _setTranslateY(mixed $arg0)
* @method UIxStackPane _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxStackPane setBaselineOffset($mixed)
* @method UIxStackPane _setClip(php\gui\UXNode $arg0)
* @method UIxStackPane _setDepthTest( $arg0)
* @method UIxStackPane _setScaleZ(mixed $arg0)
* @method UIxStackPane _setMouseTransparent(mixed $arg0)
* @method UIxStackPane _setTranslateZ(mixed $arg0)
* @method UIxStackPane _setCacheHint( $arg0)
* @method UIxStackPane setContentBias($mixed)
* @method UIxStackPane setParent($mixed)
* @method UIxStackPane _setSize(array $arg0)
* @method UIxStackPane setLayoutBounds($mixed)
* @method UIxStackPane _setWidth(mixed $arg0)
* @method UIxStackPane setScene($mixed)
* @method UIxStackPane setBoundsInParent($mixed)
* @method UIxStackPane _setX(mixed $arg0)
* @method UIxStackPane _setY(mixed $arg0)
* @method UIxStackPane _setUserData(mixed $arg0)
* @method UIxStackPane _setCursor(mixed $arg0)
* @method UIxStackPane _setScale(mixed $arg0)
* @method UIxStackPane _setHeight(mixed $arg0)
* @method UIxStackPane setWindow($mixed)
* @method UIxStackPane _setPosition(array $arg0)
* @method UIxStackPane _setEnabled(mixed $arg0)
* @method UIxStackPane setForm($mixed)
* @method UIxStackPane _setScreenPosition(array $arg0)
* @method UIxStackPane _setScreenY(mixed $arg0)
* @method UIxStackPane _setScreenX(mixed $arg0)
* @method UIxStackPane _setRightAnchor(mixed $arg0)
* @method UIxStackPane _setLeftAnchor(mixed $arg0)
* @method UIxStackPane _setClassesString(mixed $arg0)
* @method UIxStackPane _setAnchorFlags(array $arg0)
* @method UIxStackPane _setAnchors(array $arg0)
* @method UIxStackPane _setBottomAnchor(mixed $arg0)
* @method UIxStackPane _setTopAnchor(mixed $arg0)
* @method UIxStackPane setEffects($mixed) */

class UIxStackPane extends UXStackPane {
    use Cascadable;
}
