<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\layout\UXTilePane;

/**
* @method UIxTilePane _setAlignment( $arg0)
* @method UIxTilePane _setHgap(mixed $arg0)
* @method UIxTilePane _setVgap(mixed $arg0)
* @method UIxTilePane _setPrefRows(mixed $arg0)
* @method UIxTilePane _setPrefColumns(mixed $arg0)
* @method UIxTilePane _setPrefTileHeight(mixed $arg0)
* @method UIxTilePane _setPrefTileWidth(mixed $arg0)
* @method UIxTilePane _setOrientation( $arg0)
* @method UIxTilePane _setTileAlignment( $arg0)
* @method UIxTilePane setChildren($mixed)
* @method UIxTilePane _setMinHeight(mixed $arg0)
* @method UIxTilePane _setMaxWidth(mixed $arg0)
* @method UIxTilePane _setMinWidth(mixed $arg0)
* @method UIxTilePane _setMaxHeight(mixed $arg0)
* @method UIxTilePane _setPadding(mixed $arg0)
* @method UIxTilePane _setMaxSize(array $arg0)
* @method UIxTilePane _setMinSize(array $arg0)
* @method UIxTilePane _setBackgroundColor(mixed $arg0)
* @method UIxTilePane _setPaddingTop(mixed $arg0)
* @method UIxTilePane _setPaddingLeft(mixed $arg0)
* @method UIxTilePane _setPaddingBottom(mixed $arg0)
* @method UIxTilePane setPrefSize($mixed)
* @method UIxTilePane _setPaddingRight(mixed $arg0)
* @method UIxTilePane setStylesheets($mixed)
* @method UIxTilePane setChildrenUnmodifiable($mixed)
* @method UIxTilePane _setCache(mixed $arg0)
* @method UIxTilePane _setRotate(mixed $arg0)
* @method UIxTilePane _setId(mixed $arg0)
* @method UIxTilePane _setScaleX(mixed $arg0)
* @method UIxTilePane _setScaleY(mixed $arg0)
* @method UIxTilePane _setTranslateX(mixed $arg0)
* @method UIxTilePane _setTranslateY(mixed $arg0)
* @method UIxTilePane _setOpacity(mixed $arg0)
* @method UIxTilePane setDisabled($mixed)
* @method UIxTilePane _setManaged(mixed $arg0)
* @method UIxTilePane _setVisible(mixed $arg0)
* @method UIxTilePane _setStyle(mixed $arg0)
* @method UIxTilePane setFocused($mixed)
* @method UIxTilePane setHover($mixed)
* @method UIxTilePane setPressed($mixed)
* @method UIxTilePane _setBlendMode( $arg0)
* @method UIxTilePane _setPickOnBounds(mixed $arg0)
* @method UIxTilePane setClasses($mixed)
* @method UIxTilePane _setFocusTraversable(mixed $arg0)
* @method UIxTilePane setResizable($mixed)
* @method UIxTilePane _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxTilePane setBaselineOffset($mixed)
* @method UIxTilePane _setClip(php\gui\UXNode $arg0)
* @method UIxTilePane _setDepthTest( $arg0)
* @method UIxTilePane _setScaleZ(mixed $arg0)
* @method UIxTilePane _setTranslateZ(mixed $arg0)
* @method UIxTilePane _setCacheHint( $arg0)
* @method UIxTilePane _setMouseTransparent(mixed $arg0)
* @method UIxTilePane setContentBias($mixed)
* @method UIxTilePane setParent($mixed)
* @method UIxTilePane _setSize(array $arg0)
* @method UIxTilePane setLayoutBounds($mixed)
* @method UIxTilePane _setWidth(mixed $arg0)
* @method UIxTilePane setScene($mixed)
* @method UIxTilePane _setX(mixed $arg0)
* @method UIxTilePane _setY(mixed $arg0)
* @method UIxTilePane setBoundsInParent($mixed)
* @method UIxTilePane _setUserData(mixed $arg0)
* @method UIxTilePane _setCursor(mixed $arg0)
* @method UIxTilePane _setScale(mixed $arg0)
* @method UIxTilePane _setHeight(mixed $arg0)
* @method UIxTilePane setWindow($mixed)
* @method UIxTilePane _setPosition(array $arg0)
* @method UIxTilePane setForm($mixed)
* @method UIxTilePane _setEnabled(mixed $arg0)
* @method UIxTilePane _setScreenPosition(array $arg0)
* @method UIxTilePane _setScreenY(mixed $arg0)
* @method UIxTilePane _setScreenX(mixed $arg0)
* @method UIxTilePane setEffects($mixed)
* @method UIxTilePane _setLeftAnchor(mixed $arg0)
* @method UIxTilePane _setTopAnchor(mixed $arg0)
* @method UIxTilePane _setClassesString(mixed $arg0)
* @method UIxTilePane _setAnchors(array $arg0)
* @method UIxTilePane _setRightAnchor(mixed $arg0)
* @method UIxTilePane _setBottomAnchor(mixed $arg0)
* @method UIxTilePane _setAnchorFlags(array $arg0) */

class UIxTilePane extends UXTilePane {
    use Cascadable;
}
