<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXTabPane;

/**
* @method UIxTabPane setTabs($mixed)
* @method UIxTabPane _setSide( $arg0)
* @method UIxTabPane _setTabMaxHeight(mixed $arg0)
* @method UIxTabPane _setTabMaxWidth(mixed $arg0)
* @method UIxTabPane _setTabClosingPolicy( $arg0)
* @method UIxTabPane _setTabMinWidth(mixed $arg0)
* @method UIxTabPane _setTabMinHeight(mixed $arg0)
* @method UIxTabPane _setSelectedIndex(mixed $arg0)
* @method UIxTabPane _setSelectedTab(php\gui\UXTab $arg0)
* @method UIxTabPane setResizable($mixed)
* @method UIxTabPane _setTooltip(php\gui\UXTooltip $arg0)
* @method UIxTabPane _setContextMenu(php\gui\UXContextMenu $arg0)
* @method UIxTabPane _setTooltipText(mixed $arg0)
* @method UIxTabPane _setMaxWidth(mixed $arg0)
* @method UIxTabPane _setMinWidth(mixed $arg0)
* @method UIxTabPane _setMinHeight(mixed $arg0)
* @method UIxTabPane _setMaxHeight(mixed $arg0)
* @method UIxTabPane _setPadding(mixed $arg0)
* @method UIxTabPane _setMinSize(array $arg0)
* @method UIxTabPane _setMaxSize(array $arg0)
* @method UIxTabPane _setBackgroundColor(mixed $arg0)
* @method UIxTabPane _setPaddingTop(mixed $arg0)
* @method UIxTabPane _setPaddingRight(mixed $arg0)
* @method UIxTabPane setPrefSize($mixed)
* @method UIxTabPane _setPaddingLeft(mixed $arg0)
* @method UIxTabPane _setPaddingBottom(mixed $arg0)
* @method UIxTabPane setStylesheets($mixed)
* @method UIxTabPane setChildrenUnmodifiable($mixed)
* @method UIxTabPane _setCache(mixed $arg0)
* @method UIxTabPane _setRotate(mixed $arg0)
* @method UIxTabPane _setId(mixed $arg0)
* @method UIxTabPane _setOpacity(mixed $arg0)
* @method UIxTabPane _setVisible(mixed $arg0)
* @method UIxTabPane setDisabled($mixed)
* @method UIxTabPane _setManaged(mixed $arg0)
* @method UIxTabPane _setStyle(mixed $arg0)
* @method UIxTabPane setFocused($mixed)
* @method UIxTabPane setHover($mixed)
* @method UIxTabPane setPressed($mixed)
* @method UIxTabPane _setFocusTraversable(mixed $arg0)
* @method UIxTabPane setClasses($mixed)
* @method UIxTabPane _setPickOnBounds(mixed $arg0)
* @method UIxTabPane _setBlendMode( $arg0)
* @method UIxTabPane _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxTabPane setBaselineOffset($mixed)
* @method UIxTabPane _setClip(php\gui\UXNode $arg0)
* @method UIxTabPane _setScaleX(mixed $arg0)
* @method UIxTabPane _setScaleY(mixed $arg0)
* @method UIxTabPane _setTranslateX(mixed $arg0)
* @method UIxTabPane _setTranslateY(mixed $arg0)
* @method UIxTabPane _setScaleZ(mixed $arg0)
* @method UIxTabPane _setDepthTest( $arg0)
* @method UIxTabPane _setTranslateZ(mixed $arg0)
* @method UIxTabPane _setMouseTransparent(mixed $arg0)
* @method UIxTabPane _setCacheHint( $arg0)
* @method UIxTabPane setContentBias($mixed)
* @method UIxTabPane setParent($mixed)
* @method UIxTabPane _setSize(array $arg0)
* @method UIxTabPane _setWidth(mixed $arg0)
* @method UIxTabPane setScene($mixed)
* @method UIxTabPane setLayoutBounds($mixed)
* @method UIxTabPane _setX(mixed $arg0)
* @method UIxTabPane _setY(mixed $arg0)
* @method UIxTabPane setBoundsInParent($mixed)
* @method UIxTabPane _setUserData(mixed $arg0)
* @method UIxTabPane _setCursor(mixed $arg0)
* @method UIxTabPane _setPosition(array $arg0)
* @method UIxTabPane _setHeight(mixed $arg0)
* @method UIxTabPane setWindow($mixed)
* @method UIxTabPane _setScale(mixed $arg0)
* @method UIxTabPane _setEnabled(mixed $arg0)
* @method UIxTabPane setForm($mixed)
* @method UIxTabPane _setScreenPosition(array $arg0)
* @method UIxTabPane _setScreenX(mixed $arg0)
* @method UIxTabPane _setScreenY(mixed $arg0)
* @method UIxTabPane _setTopAnchor(mixed $arg0)
* @method UIxTabPane _setBottomAnchor(mixed $arg0)
* @method UIxTabPane _setRightAnchor(mixed $arg0)
* @method UIxTabPane _setAnchors(array $arg0)
* @method UIxTabPane _setClassesString(mixed $arg0)
* @method UIxTabPane _setAnchorFlags(array $arg0)
* @method UIxTabPane _setLeftAnchor(mixed $arg0)
* @method UIxTabPane setEffects($mixed) */

class UIxTabPane extends UXTabPane {
    use Cascadable;
}
