<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXTextArea;

/**
* @method UIxTextArea _setWrapText(mixed $arg0)
* @method UIxTextArea _setScrollTop(mixed $arg0)
* @method UIxTextArea _setPrefColumnCount(mixed $arg0)
* @method UIxTextArea _setScrollLeft(mixed $arg0)
* @method UIxTextArea _setPrefRowCount(mixed $arg0)
* @method UIxTextArea setLength($mixed)
* @method UIxTextArea _setText(mixed $arg0)
* @method UIxTextArea setAnchor($mixed)
* @method UIxTextArea _setEditable(mixed $arg0)
* @method UIxTextArea setCaretPosition($mixed)
* @method UIxTextArea _setPromptText(mixed $arg0)
* @method UIxTextArea _setSelectedText(mixed $arg0)
* @method UIxTextArea _setFont(php\gui\text\UXFont $arg0)
* @method UIxTextArea setSelection($mixed)
* @method UIxTextArea setResizable($mixed)
* @method UIxTextArea _setTooltip(php\gui\UXTooltip $arg0)
* @method UIxTextArea _setContextMenu(php\gui\UXContextMenu $arg0)
* @method UIxTextArea _setTooltipText(mixed $arg0)
* @method UIxTextArea _setMinWidth(mixed $arg0)
* @method UIxTextArea _setMaxWidth(mixed $arg0)
* @method UIxTextArea _setMinHeight(mixed $arg0)
* @method UIxTextArea _setMaxHeight(mixed $arg0)
* @method UIxTextArea _setPadding(mixed $arg0)
* @method UIxTextArea _setMinSize(array $arg0)
* @method UIxTextArea _setMaxSize(array $arg0)
* @method UIxTextArea _setBackgroundColor(mixed $arg0)
* @method UIxTextArea _setPaddingRight(mixed $arg0)
* @method UIxTextArea _setPaddingTop(mixed $arg0)
* @method UIxTextArea _setPaddingBottom(mixed $arg0)
* @method UIxTextArea _setPaddingLeft(mixed $arg0)
* @method UIxTextArea setPrefSize($mixed)
* @method UIxTextArea setStylesheets($mixed)
* @method UIxTextArea setChildrenUnmodifiable($mixed)
* @method UIxTextArea _setCache(mixed $arg0)
* @method UIxTextArea _setRotate(mixed $arg0)
* @method UIxTextArea _setId(mixed $arg0)
* @method UIxTextArea _setOpacity(mixed $arg0)
* @method UIxTextArea setFocused($mixed)
* @method UIxTextArea _setStyle(mixed $arg0)
* @method UIxTextArea _setVisible(mixed $arg0)
* @method UIxTextArea setHover($mixed)
* @method UIxTextArea setDisabled($mixed)
* @method UIxTextArea _setManaged(mixed $arg0)
* @method UIxTextArea setPressed($mixed)
* @method UIxTextArea _setFocusTraversable(mixed $arg0)
* @method UIxTextArea setClasses($mixed)
* @method UIxTextArea _setBlendMode( $arg0)
* @method UIxTextArea _setPickOnBounds(mixed $arg0)
* @method UIxTextArea _setScaleX(mixed $arg0)
* @method UIxTextArea _setScaleY(mixed $arg0)
* @method UIxTextArea _setTranslateX(mixed $arg0)
* @method UIxTextArea _setTranslateY(mixed $arg0)
* @method UIxTextArea _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxTextArea setBaselineOffset($mixed)
* @method UIxTextArea _setScaleZ(mixed $arg0)
* @method UIxTextArea _setClip(php\gui\UXNode $arg0)
* @method UIxTextArea _setDepthTest( $arg0)
* @method UIxTextArea _setTranslateZ(mixed $arg0)
* @method UIxTextArea _setMouseTransparent(mixed $arg0)
* @method UIxTextArea _setCacheHint( $arg0)
* @method UIxTextArea setContentBias($mixed)
* @method UIxTextArea setParent($mixed)
* @method UIxTextArea _setSize(array $arg0)
* @method UIxTextArea _setWidth(mixed $arg0)
* @method UIxTextArea setScene($mixed)
* @method UIxTextArea setLayoutBounds($mixed)
* @method UIxTextArea setBoundsInParent($mixed)
* @method UIxTextArea _setX(mixed $arg0)
* @method UIxTextArea _setY(mixed $arg0)
* @method UIxTextArea _setUserData(mixed $arg0)
* @method UIxTextArea _setCursor(mixed $arg0)
* @method UIxTextArea _setScale(mixed $arg0)
* @method UIxTextArea _setHeight(mixed $arg0)
* @method UIxTextArea setWindow($mixed)
* @method UIxTextArea _setPosition(array $arg0)
* @method UIxTextArea _setEnabled(mixed $arg0)
* @method UIxTextArea setForm($mixed)
* @method UIxTextArea _setScreenPosition(array $arg0)
* @method UIxTextArea _setScreenX(mixed $arg0)
* @method UIxTextArea _setScreenY(mixed $arg0)
* @method UIxTextArea _setAnchorFlags(array $arg0)
* @method UIxTextArea _setTopAnchor(mixed $arg0)
* @method UIxTextArea _setAnchors(array $arg0)
* @method UIxTextArea _setRightAnchor(mixed $arg0)
* @method UIxTextArea _setClassesString(mixed $arg0)
* @method UIxTextArea _setLeftAnchor(mixed $arg0)
* @method UIxTextArea setEffects($mixed)
* @method UIxTextArea _setBottomAnchor(mixed $arg0) */

class UIxTextArea extends UXTextArea {
    use Cascadable;
}
