<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXToggleButton;

/**
* @method UIxToggleButton _setSelected(mixed $arg0)
* @method UIxToggleButton _setToggleGroup(php\gui\UXToggleGroup $arg0)
* @method UIxToggleButton setArmed($mixed)
* @method UIxToggleButton _setAlignment( $arg0)
* @method UIxToggleButton _setText(mixed $arg0)
* @method UIxToggleButton _setWrapText(mixed $arg0)
* @method UIxToggleButton _setGraphicTextGap(mixed $arg0)
* @method UIxToggleButton _setTextAlignment( $arg0)
* @method UIxToggleButton _setContentDisplay( $arg0)
* @method UIxToggleButton _setMnemonicParsing(mixed $arg0)
* @method UIxToggleButton _setEllipsisString(mixed $arg0)
* @method UIxToggleButton _setUnderline(mixed $arg0)
* @method UIxToggleButton _setFont(php\gui\text\UXFont $arg0)
* @method UIxToggleButton _setGraphic(php\gui\UXNode $arg0)
* @method UIxToggleButton _setTextColor(mixed $arg0)
* @method UIxToggleButton setResizable($mixed)
* @method UIxToggleButton _setTooltip(php\gui\UXTooltip $arg0)
* @method UIxToggleButton _setContextMenu(php\gui\UXContextMenu $arg0)
* @method UIxToggleButton _setTooltipText(mixed $arg0)
* @method UIxToggleButton _setMinWidth(mixed $arg0)
* @method UIxToggleButton _setMaxWidth(mixed $arg0)
* @method UIxToggleButton _setMinHeight(mixed $arg0)
* @method UIxToggleButton _setMaxHeight(mixed $arg0)
* @method UIxToggleButton _setPadding(mixed $arg0)
* @method UIxToggleButton _setMinSize(array $arg0)
* @method UIxToggleButton _setMaxSize(array $arg0)
* @method UIxToggleButton _setBackgroundColor(mixed $arg0)
* @method UIxToggleButton setPrefSize($mixed)
* @method UIxToggleButton _setPaddingTop(mixed $arg0)
* @method UIxToggleButton _setPaddingBottom(mixed $arg0)
* @method UIxToggleButton _setPaddingRight(mixed $arg0)
* @method UIxToggleButton _setPaddingLeft(mixed $arg0)
* @method UIxToggleButton setStylesheets($mixed)
* @method UIxToggleButton setChildrenUnmodifiable($mixed)
* @method UIxToggleButton _setCache(mixed $arg0)
* @method UIxToggleButton _setRotate(mixed $arg0)
* @method UIxToggleButton _setId(mixed $arg0)
* @method UIxToggleButton _setOpacity(mixed $arg0)
* @method UIxToggleButton setDisabled($mixed)
* @method UIxToggleButton _setVisible(mixed $arg0)
* @method UIxToggleButton _setManaged(mixed $arg0)
* @method UIxToggleButton _setStyle(mixed $arg0)
* @method UIxToggleButton setFocused($mixed)
* @method UIxToggleButton setPressed($mixed)
* @method UIxToggleButton setHover($mixed)
* @method UIxToggleButton _setFocusTraversable(mixed $arg0)
* @method UIxToggleButton _setPickOnBounds(mixed $arg0)
* @method UIxToggleButton setClasses($mixed)
* @method UIxToggleButton _setBlendMode( $arg0)
* @method UIxToggleButton _setScaleX(mixed $arg0)
* @method UIxToggleButton _setScaleY(mixed $arg0)
* @method UIxToggleButton _setTranslateX(mixed $arg0)
* @method UIxToggleButton _setTranslateY(mixed $arg0)
* @method UIxToggleButton _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxToggleButton setBaselineOffset($mixed)
* @method UIxToggleButton _setClip(php\gui\UXNode $arg0)
* @method UIxToggleButton _setDepthTest( $arg0)
* @method UIxToggleButton _setScaleZ(mixed $arg0)
* @method UIxToggleButton _setTranslateZ(mixed $arg0)
* @method UIxToggleButton _setCacheHint( $arg0)
* @method UIxToggleButton _setMouseTransparent(mixed $arg0)
* @method UIxToggleButton setContentBias($mixed)
* @method UIxToggleButton setParent($mixed)
* @method UIxToggleButton _setSize(array $arg0)
* @method UIxToggleButton setScene($mixed)
* @method UIxToggleButton _setWidth(mixed $arg0)
* @method UIxToggleButton setLayoutBounds($mixed)
* @method UIxToggleButton setBoundsInParent($mixed)
* @method UIxToggleButton _setX(mixed $arg0)
* @method UIxToggleButton _setY(mixed $arg0)
* @method UIxToggleButton _setUserData(mixed $arg0)
* @method UIxToggleButton _setCursor(mixed $arg0)
* @method UIxToggleButton _setScale(mixed $arg0)
* @method UIxToggleButton _setPosition(array $arg0)
* @method UIxToggleButton _setHeight(mixed $arg0)
* @method UIxToggleButton setWindow($mixed)
* @method UIxToggleButton setForm($mixed)
* @method UIxToggleButton _setEnabled(mixed $arg0)
* @method UIxToggleButton _setScreenPosition(array $arg0)
* @method UIxToggleButton _setScreenY(mixed $arg0)
* @method UIxToggleButton _setScreenX(mixed $arg0)
* @method UIxToggleButton _setClassesString(mixed $arg0)
* @method UIxToggleButton _setAnchorFlags(array $arg0)
* @method UIxToggleButton _setLeftAnchor(mixed $arg0)
* @method UIxToggleButton _setTopAnchor(mixed $arg0)
* @method UIxToggleButton _setBottomAnchor(mixed $arg0)
* @method UIxToggleButton _setRightAnchor(mixed $arg0)
* @method UIxToggleButton _setAnchors(array $arg0)
* @method UIxToggleButton setEffects($mixed) */

class UIxToggleButton extends UXToggleButton {
    use Cascadable;
}
