<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXTitledPane;

/**
* @method UIxTitledPane _setContent(php\gui\UXNode $arg0)
* @method UIxTitledPane _setAnimated(mixed $arg0)
* @method UIxTitledPane _setExpanded(mixed $arg0)
* @method UIxTitledPane _setCollapsible(mixed $arg0)
* @method UIxTitledPane _setText(mixed $arg0)
* @method UIxTitledPane _setAlignment( $arg0)
* @method UIxTitledPane _setWrapText(mixed $arg0)
* @method UIxTitledPane _setContentDisplay( $arg0)
* @method UIxTitledPane _setGraphicTextGap(mixed $arg0)
* @method UIxTitledPane _setTextAlignment( $arg0)
* @method UIxTitledPane _setMnemonicParsing(mixed $arg0)
* @method UIxTitledPane _setEllipsisString(mixed $arg0)
* @method UIxTitledPane _setUnderline(mixed $arg0)
* @method UIxTitledPane _setFont(php\gui\text\UXFont $arg0)
* @method UIxTitledPane _setGraphic(php\gui\UXNode $arg0)
* @method UIxTitledPane _setTextColor(mixed $arg0)
* @method UIxTitledPane setResizable($mixed)
* @method UIxTitledPane _setTooltip(php\gui\UXTooltip $arg0)
* @method UIxTitledPane _setContextMenu(php\gui\UXContextMenu $arg0)
* @method UIxTitledPane _setTooltipText(mixed $arg0)
* @method UIxTitledPane _setMinHeight(mixed $arg0)
* @method UIxTitledPane _setMaxWidth(mixed $arg0)
* @method UIxTitledPane _setMinWidth(mixed $arg0)
* @method UIxTitledPane _setMaxHeight(mixed $arg0)
* @method UIxTitledPane _setPadding(mixed $arg0)
* @method UIxTitledPane _setMinSize(array $arg0)
* @method UIxTitledPane _setMaxSize(array $arg0)
* @method UIxTitledPane _setBackgroundColor(mixed $arg0)
* @method UIxTitledPane _setPaddingTop(mixed $arg0)
* @method UIxTitledPane _setPaddingLeft(mixed $arg0)
* @method UIxTitledPane _setPaddingRight(mixed $arg0)
* @method UIxTitledPane setPrefSize($mixed)
* @method UIxTitledPane _setPaddingBottom(mixed $arg0)
* @method UIxTitledPane setStylesheets($mixed)
* @method UIxTitledPane setChildrenUnmodifiable($mixed)
* @method UIxTitledPane _setCache(mixed $arg0)
* @method UIxTitledPane _setRotate(mixed $arg0)
* @method UIxTitledPane _setId(mixed $arg0)
* @method UIxTitledPane _setScaleX(mixed $arg0)
* @method UIxTitledPane _setScaleY(mixed $arg0)
* @method UIxTitledPane _setTranslateX(mixed $arg0)
* @method UIxTitledPane _setTranslateY(mixed $arg0)
* @method UIxTitledPane _setOpacity(mixed $arg0)
* @method UIxTitledPane _setStyle(mixed $arg0)
* @method UIxTitledPane setDisabled($mixed)
* @method UIxTitledPane _setManaged(mixed $arg0)
* @method UIxTitledPane _setVisible(mixed $arg0)
* @method UIxTitledPane setHover($mixed)
* @method UIxTitledPane setFocused($mixed)
* @method UIxTitledPane setPressed($mixed)
* @method UIxTitledPane _setFocusTraversable(mixed $arg0)
* @method UIxTitledPane _setBlendMode( $arg0)
* @method UIxTitledPane setClasses($mixed)
* @method UIxTitledPane _setPickOnBounds(mixed $arg0)
* @method UIxTitledPane _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxTitledPane setBaselineOffset($mixed)
* @method UIxTitledPane _setClip(php\gui\UXNode $arg0)
* @method UIxTitledPane _setDepthTest( $arg0)
* @method UIxTitledPane _setScaleZ(mixed $arg0)
* @method UIxTitledPane _setTranslateZ(mixed $arg0)
* @method UIxTitledPane _setMouseTransparent(mixed $arg0)
* @method UIxTitledPane _setCacheHint( $arg0)
* @method UIxTitledPane setContentBias($mixed)
* @method UIxTitledPane setParent($mixed)
* @method UIxTitledPane _setSize(array $arg0)
* @method UIxTitledPane setLayoutBounds($mixed)
* @method UIxTitledPane _setWidth(mixed $arg0)
* @method UIxTitledPane setScene($mixed)
* @method UIxTitledPane _setX(mixed $arg0)
* @method UIxTitledPane _setY(mixed $arg0)
* @method UIxTitledPane setBoundsInParent($mixed)
* @method UIxTitledPane _setUserData(mixed $arg0)
* @method UIxTitledPane _setCursor(mixed $arg0)
* @method UIxTitledPane _setPosition(array $arg0)
* @method UIxTitledPane _setScale(mixed $arg0)
* @method UIxTitledPane _setHeight(mixed $arg0)
* @method UIxTitledPane setWindow($mixed)
* @method UIxTitledPane setForm($mixed)
* @method UIxTitledPane _setEnabled(mixed $arg0)
* @method UIxTitledPane _setScreenPosition(array $arg0)
* @method UIxTitledPane _setScreenX(mixed $arg0)
* @method UIxTitledPane _setScreenY(mixed $arg0)
* @method UIxTitledPane _setAnchorFlags(array $arg0)
* @method UIxTitledPane _setLeftAnchor(mixed $arg0)
* @method UIxTitledPane setEffects($mixed)
* @method UIxTitledPane _setBottomAnchor(mixed $arg0)
* @method UIxTitledPane _setTopAnchor(mixed $arg0)
* @method UIxTitledPane _setAnchors(array $arg0)
* @method UIxTitledPane _setRightAnchor(mixed $arg0)
* @method UIxTitledPane _setClassesString(mixed $arg0) */

class UIxTitledPane extends UXTitledPane {
    use Cascadable;
}
