<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXTextField;

/**
* @method UIxTextField _setAlignment( $arg0)
* @method UIxTextField _setPrefColumnCount(mixed $arg0)
* @method UIxTextField setLength($mixed)
* @method UIxTextField _setText(mixed $arg0)
* @method UIxTextField setAnchor($mixed)
* @method UIxTextField _setEditable(mixed $arg0)
* @method UIxTextField _setSelectedText(mixed $arg0)
* @method UIxTextField _setPromptText(mixed $arg0)
* @method UIxTextField setCaretPosition($mixed)
* @method UIxTextField _setFont(php\gui\text\UXFont $arg0)
* @method UIxTextField setSelection($mixed)
* @method UIxTextField setResizable($mixed)
* @method UIxTextField _setTooltip(php\gui\UXTooltip $arg0)
* @method UIxTextField _setContextMenu(php\gui\UXContextMenu $arg0)
* @method UIxTextField _setTooltipText(mixed $arg0)
* @method UIxTextField _setMinHeight(mixed $arg0)
* @method UIxTextField _setMinWidth(mixed $arg0)
* @method UIxTextField _setMaxWidth(mixed $arg0)
* @method UIxTextField _setMaxHeight(mixed $arg0)
* @method UIxTextField _setPadding(mixed $arg0)
* @method UIxTextField _setMinSize(array $arg0)
* @method UIxTextField _setMaxSize(array $arg0)
* @method UIxTextField _setBackgroundColor(mixed $arg0)
* @method UIxTextField _setPaddingRight(mixed $arg0)
* @method UIxTextField _setPaddingBottom(mixed $arg0)
* @method UIxTextField _setPaddingTop(mixed $arg0)
* @method UIxTextField _setPaddingLeft(mixed $arg0)
* @method UIxTextField setPrefSize($mixed)
* @method UIxTextField setStylesheets($mixed)
* @method UIxTextField setChildrenUnmodifiable($mixed)
* @method UIxTextField _setCache(mixed $arg0)
* @method UIxTextField _setRotate(mixed $arg0)
* @method UIxTextField _setId(mixed $arg0)
* @method UIxTextField _setOpacity(mixed $arg0)
* @method UIxTextField setPressed($mixed)
* @method UIxTextField _setStyle(mixed $arg0)
* @method UIxTextField _setVisible(mixed $arg0)
* @method UIxTextField setDisabled($mixed)
* @method UIxTextField setFocused($mixed)
* @method UIxTextField _setManaged(mixed $arg0)
* @method UIxTextField setHover($mixed)
* @method UIxTextField setClasses($mixed)
* @method UIxTextField _setPickOnBounds(mixed $arg0)
* @method UIxTextField _setBlendMode( $arg0)
* @method UIxTextField _setFocusTraversable(mixed $arg0)
* @method UIxTextField _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxTextField setBaselineOffset($mixed)
* @method UIxTextField _setClip(php\gui\UXNode $arg0)
* @method UIxTextField _setScaleX(mixed $arg0)
* @method UIxTextField _setScaleY(mixed $arg0)
* @method UIxTextField _setTranslateX(mixed $arg0)
* @method UIxTextField _setTranslateY(mixed $arg0)
* @method UIxTextField _setDepthTest( $arg0)
* @method UIxTextField _setScaleZ(mixed $arg0)
* @method UIxTextField _setTranslateZ(mixed $arg0)
* @method UIxTextField _setMouseTransparent(mixed $arg0)
* @method UIxTextField _setCacheHint( $arg0)
* @method UIxTextField setContentBias($mixed)
* @method UIxTextField setParent($mixed)
* @method UIxTextField _setSize(array $arg0)
* @method UIxTextField setLayoutBounds($mixed)
* @method UIxTextField _setWidth(mixed $arg0)
* @method UIxTextField setScene($mixed)
* @method UIxTextField setBoundsInParent($mixed)
* @method UIxTextField _setX(mixed $arg0)
* @method UIxTextField _setY(mixed $arg0)
* @method UIxTextField _setCursor(mixed $arg0)
* @method UIxTextField _setUserData(mixed $arg0)
* @method UIxTextField _setScale(mixed $arg0)
* @method UIxTextField _setHeight(mixed $arg0)
* @method UIxTextField setWindow($mixed)
* @method UIxTextField _setPosition(array $arg0)
* @method UIxTextField setForm($mixed)
* @method UIxTextField _setEnabled(mixed $arg0)
* @method UIxTextField _setScreenPosition(array $arg0)
* @method UIxTextField _setScreenY(mixed $arg0)
* @method UIxTextField _setScreenX(mixed $arg0)
* @method UIxTextField _setRightAnchor(mixed $arg0)
* @method UIxTextField _setBottomAnchor(mixed $arg0)
* @method UIxTextField setEffects($mixed)
* @method UIxTextField _setClassesString(mixed $arg0)
* @method UIxTextField _setAnchors(array $arg0)
* @method UIxTextField _setLeftAnchor(mixed $arg0)
* @method UIxTextField _setAnchorFlags(array $arg0)
* @method UIxTextField _setTopAnchor(mixed $arg0) */

class UIxTextField extends UXTextField {
    use Cascadable;
}
