<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXTreeView;

/**
* @method UIxTreeView _setRoot(php\gui\UXTreeItem $arg0)
* @method UIxTreeView setRootVisible($mixed)
* @method UIxTreeView _setEditable(mixed $arg0)
* @method UIxTreeView setExpandedItemCount($mixed)
* @method UIxTreeView _setFixedCellSize(mixed $arg0)
* @method UIxTreeView setEditingItem($mixed)
* @method UIxTreeView _setSelectedIndexes(array $arg0)
* @method UIxTreeView _setMultipleSelection(mixed $arg0)
* @method UIxTreeView _setSelectedItems(traversable $arg0)
* @method UIxTreeView setExpandedItems($mixed)
* @method UIxTreeView _setFocusedItem(php\gui\UXTreeItem $arg0)
* @method UIxTreeView setResizable($mixed)
* @method UIxTreeView _setTooltip(php\gui\UXTooltip $arg0)
* @method UIxTreeView _setContextMenu(php\gui\UXContextMenu $arg0)
* @method UIxTreeView _setTooltipText(mixed $arg0)
* @method UIxTreeView _setMinHeight(mixed $arg0)
* @method UIxTreeView _setMaxWidth(mixed $arg0)
* @method UIxTreeView _setMinWidth(mixed $arg0)
* @method UIxTreeView _setPadding(mixed $arg0)
* @method UIxTreeView _setMaxHeight(mixed $arg0)
* @method UIxTreeView _setMaxSize(array $arg0)
* @method UIxTreeView _setMinSize(array $arg0)
* @method UIxTreeView _setBackgroundColor(mixed $arg0)
* @method UIxTreeView _setPaddingLeft(mixed $arg0)
* @method UIxTreeView _setPaddingBottom(mixed $arg0)
* @method UIxTreeView _setPaddingRight(mixed $arg0)
* @method UIxTreeView _setPaddingTop(mixed $arg0)
* @method UIxTreeView setPrefSize($mixed)
* @method UIxTreeView setStylesheets($mixed)
* @method UIxTreeView setChildrenUnmodifiable($mixed)
* @method UIxTreeView _setCache(mixed $arg0)
* @method UIxTreeView _setRotate(mixed $arg0)
* @method UIxTreeView _setId(mixed $arg0)
* @method UIxTreeView _setOpacity(mixed $arg0)
* @method UIxTreeView _setVisible(mixed $arg0)
* @method UIxTreeView _setManaged(mixed $arg0)
* @method UIxTreeView setDisabled($mixed)
* @method UIxTreeView _setStyle(mixed $arg0)
* @method UIxTreeView setFocused($mixed)
* @method UIxTreeView setPressed($mixed)
* @method UIxTreeView setHover($mixed)
* @method UIxTreeView _setFocusTraversable(mixed $arg0)
* @method UIxTreeView _setBlendMode( $arg0)
* @method UIxTreeView setClasses($mixed)
* @method UIxTreeView _setPickOnBounds(mixed $arg0)
* @method UIxTreeView _setScaleX(mixed $arg0)
* @method UIxTreeView _setScaleY(mixed $arg0)
* @method UIxTreeView _setTranslateX(mixed $arg0)
* @method UIxTreeView _setTranslateY(mixed $arg0)
* @method UIxTreeView _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxTreeView setBaselineOffset($mixed)
* @method UIxTreeView _setClip(php\gui\UXNode $arg0)
* @method UIxTreeView _setDepthTest( $arg0)
* @method UIxTreeView _setScaleZ(mixed $arg0)
* @method UIxTreeView _setTranslateZ(mixed $arg0)
* @method UIxTreeView _setMouseTransparent(mixed $arg0)
* @method UIxTreeView _setCacheHint( $arg0)
* @method UIxTreeView setContentBias($mixed)
* @method UIxTreeView setParent($mixed)
* @method UIxTreeView _setSize(array $arg0)
* @method UIxTreeView setLayoutBounds($mixed)
* @method UIxTreeView _setWidth(mixed $arg0)
* @method UIxTreeView setScene($mixed)
* @method UIxTreeView _setY(mixed $arg0)
* @method UIxTreeView _setX(mixed $arg0)
* @method UIxTreeView setBoundsInParent($mixed)
* @method UIxTreeView _setUserData(mixed $arg0)
* @method UIxTreeView _setCursor(mixed $arg0)
* @method UIxTreeView _setPosition(array $arg0)
* @method UIxTreeView _setScale(mixed $arg0)
* @method UIxTreeView _setHeight(mixed $arg0)
* @method UIxTreeView setWindow($mixed)
* @method UIxTreeView _setEnabled(mixed $arg0)
* @method UIxTreeView setForm($mixed)
* @method UIxTreeView _setScreenPosition(array $arg0)
* @method UIxTreeView _setScreenX(mixed $arg0)
* @method UIxTreeView _setScreenY(mixed $arg0)
* @method UIxTreeView _setTopAnchor(mixed $arg0)
* @method UIxTreeView _setAnchors(array $arg0)
* @method UIxTreeView _setAnchorFlags(array $arg0)
* @method UIxTreeView _setRightAnchor(mixed $arg0)
* @method UIxTreeView _setBottomAnchor(mixed $arg0)
* @method UIxTreeView _setClassesString(mixed $arg0)
* @method UIxTreeView _setLeftAnchor(mixed $arg0)
* @method UIxTreeView setEffects($mixed) */

class UIxTreeView extends UXTreeView {
    use Cascadable;
}
