<?php 

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\layout\UXVBox;

/**
* @method UIxVBox _setSpacing(mixed $arg0)
* @method UIxVBox _setAlignment( $arg0)
* @method UIxVBox _setFillWidth(mixed $arg0)
* @method UIxVBox setChildren($mixed)
* @method UIxVBox _setMinHeight(mixed $arg0)
* @method UIxVBox _setMaxWidth(mixed $arg0)
* @method UIxVBox _setMinWidth(mixed $arg0)
* @method UIxVBox _setPadding(mixed $arg0)
* @method UIxVBox _setMaxHeight(mixed $arg0)
* @method UIxVBox _setMaxSize(array $arg0)
* @method UIxVBox _setMinSize(array $arg0)
* @method UIxVBox _setBackgroundColor(mixed $arg0)
* @method UIxVBox _setPaddingBottom(mixed $arg0)
* @method UIxVBox _setPaddingLeft(mixed $arg0)
* @method UIxVBox setPrefSize($mixed)
* @method UIxVBox _setPaddingRight(mixed $arg0)
* @method UIxVBox _setPaddingTop(mixed $arg0)
* @method UIxVBox setStylesheets($mixed)
* @method UIxVBox setChildrenUnmodifiable($mixed)
* @method UIxVBox _setCache(mixed $arg0)
* @method UIxVBox _setRotate(mixed $arg0)
* @method UIxVBox _setId(mixed $arg0)
* @method UIxVBox _setOpacity(mixed $arg0)
* @method UIxVBox setDisabled($mixed)
* @method UIxVBox _setStyle(mixed $arg0)
* @method UIxVBox _setManaged(mixed $arg0)
* @method UIxVBox _setVisible(mixed $arg0)
* @method UIxVBox setFocused($mixed)
* @method UIxVBox setPressed($mixed)
* @method UIxVBox setHover($mixed)
* @method UIxVBox setClasses($mixed)
* @method UIxVBox _setBlendMode( $arg0)
* @method UIxVBox _setPickOnBounds(mixed $arg0)
* @method UIxVBox _setFocusTraversable(mixed $arg0)
* @method UIxVBox setResizable($mixed)
* @method UIxVBox setBaselineOffset($mixed)
* @method UIxVBox _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxVBox _setScaleX(mixed $arg0)
* @method UIxVBox _setScaleY(mixed $arg0)
* @method UIxVBox _setTranslateX(mixed $arg0)
* @method UIxVBox _setTranslateY(mixed $arg0)
* @method UIxVBox _setClip(php\gui\UXNode $arg0)
* @method UIxVBox _setScaleZ(mixed $arg0)
* @method UIxVBox _setDepthTest( $arg0)
* @method UIxVBox _setCacheHint( $arg0)
* @method UIxVBox _setMouseTransparent(mixed $arg0)
* @method UIxVBox _setTranslateZ(mixed $arg0)
* @method UIxVBox setContentBias($mixed)
* @method UIxVBox setParent($mixed)
* @method UIxVBox _setSize(array $arg0)
* @method UIxVBox setLayoutBounds($mixed)
* @method UIxVBox _setWidth(mixed $arg0)
* @method UIxVBox setScene($mixed)
* @method UIxVBox _setY(mixed $arg0)
* @method UIxVBox _setX(mixed $arg0)
* @method UIxVBox setBoundsInParent($mixed)
* @method UIxVBox _setCursor(mixed $arg0)
* @method UIxVBox _setUserData(mixed $arg0)
* @method UIxVBox _setScale(mixed $arg0)
* @method UIxVBox _setHeight(mixed $arg0)
* @method UIxVBox setWindow($mixed)
* @method UIxVBox _setPosition(array $arg0)
* @method UIxVBox _setEnabled(mixed $arg0)
* @method UIxVBox _setScreenPosition(array $arg0)
* @method UIxVBox _setScreenY(mixed $arg0)
* @method UIxVBox _setScreenX(mixed $arg0)
* @method UIxVBox _setAnchors(array $arg0)
* @method UIxVBox _setRightAnchor(mixed $arg0)
* @method UIxVBox _setLeftAnchor(mixed $arg0)
* @method UIxVBox _setTopAnchor(mixed $arg0)
* @method UIxVBox setEffects($mixed)
* @method UIxVBox _setClassesString(mixed $arg0)
* @method UIxVBox _setAnchorFlags(array $arg0)
* @method UIxVBox _setBottomAnchor(mixed $arg0)
* @method UIxVBox setForm($mixed)
 */
class UIxVBox extends UXVBox
{
    use Cascadable;


    
}