<?php

namespace kosogroup\liver\ui\components;

use kosogroup\liver\ui\components\traits\Cascadable;
use php\gui\UXWebView;

/**
* @method UIxWebView _setMaxWidth(mixed $arg0)
* @method UIxWebView _setMinWidth(mixed $arg0)
* @method UIxWebView _setMinHeight(mixed $arg0)
* @method UIxWebView _setMaxHeight(mixed $arg0)
* @method UIxWebView _setZoom(mixed $arg0)
* @method UIxWebView setEngine($mixed)
* @method UIxWebView _setFontScale(mixed $arg0)
* @method UIxWebView _setContextMenuEnabled(mixed $arg0)
* @method UIxWebView _setFontSmoothingType( $arg0)
* @method UIxWebView _setMinSize(array $arg0)
* @method UIxWebView _setMaxSize(array $arg0)
* @method UIxWebView _setUrl(mixed $arg0)
* @method UIxWebView setStylesheets($mixed)
* @method UIxWebView setChildrenUnmodifiable($mixed)
* @method UIxWebView _setCache(mixed $arg0)
* @method UIxWebView _setRotate(mixed $arg0)
* @method UIxWebView _setId(mixed $arg0)
* @method UIxWebView _setOpacity(mixed $arg0)
* @method UIxWebView _setStyle(mixed $arg0)
* @method UIxWebView _setVisible(mixed $arg0)
* @method UIxWebView _setManaged(mixed $arg0)
* @method UIxWebView setDisabled($mixed)
* @method UIxWebView setPressed($mixed)
* @method UIxWebView setFocused($mixed)
* @method UIxWebView setHover($mixed)
* @method UIxWebView _setBlendMode( $arg0)
* @method UIxWebView setClasses($mixed)
* @method UIxWebView _setPickOnBounds(mixed $arg0)
* @method UIxWebView _setFocusTraversable(mixed $arg0)
* @method UIxWebView _setScaleX(mixed $arg0)
* @method UIxWebView _setScaleY(mixed $arg0)
* @method UIxWebView _setTranslateX(mixed $arg0)
* @method UIxWebView _setTranslateY(mixed $arg0)
* @method UIxWebView setResizable($mixed)
* @method UIxWebView _setEffect(php\gui\effect\UXEffect $arg0)
* @method UIxWebView setBaselineOffset($mixed)
* @method UIxWebView _setClip(php\gui\UXNode $arg0)
* @method UIxWebView _setDepthTest( $arg0)
* @method UIxWebView _setScaleZ(mixed $arg0)
* @method UIxWebView _setTranslateZ(mixed $arg0)
* @method UIxWebView _setMouseTransparent(mixed $arg0)
* @method UIxWebView _setCacheHint( $arg0)
* @method UIxWebView setContentBias($mixed)
* @method UIxWebView setParent($mixed)
* @method UIxWebView _setSize(array $arg0)
* @method UIxWebView _setWidth(mixed $arg0)
* @method UIxWebView setScene($mixed)
* @method UIxWebView setLayoutBounds($mixed)
* @method UIxWebView setBoundsInParent($mixed)
* @method UIxWebView _setX(mixed $arg0)
* @method UIxWebView _setY(mixed $arg0)
* @method UIxWebView _setUserData(mixed $arg0)
* @method UIxWebView _setCursor(mixed $arg0)
* @method UIxWebView _setScale(mixed $arg0)
* @method UIxWebView _setHeight(mixed $arg0)
* @method UIxWebView setWindow($mixed)
* @method UIxWebView _setPosition(array $arg0)
* @method UIxWebView _setEnabled(mixed $arg0)
* @method UIxWebView setForm($mixed)
* @method UIxWebView _setScreenPosition(array $arg0)
* @method UIxWebView _setScreenX(mixed $arg0)
* @method UIxWebView _setScreenY(mixed $arg0)
* @method UIxWebView _setAnchorFlags(array $arg0)
* @method UIxWebView _setAnchors(array $arg0)
* @method UIxWebView _setTopAnchor(mixed $arg0)
* @method UIxWebView _setLeftAnchor(mixed $arg0)
* @method UIxWebView _setBottomAnchor(mixed $arg0)
* @method UIxWebView _setRightAnchor(mixed $arg0)
* @method UIxWebView _setClassesString(mixed $arg0)
* @method UIxWebView setEffects($mixed) */

class UIxWebView extends UXWebView {
    use Cascadable;
}
